import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={projectId:'yes-card-gacha-rgb',appId:'1:496431023991:web:b62a7768104553c9958372',storageBucket:'yes-card-gacha-rgb.firebasestorage.app',apiKey:'AIzaSyB8f7LK3UR-l2UgV_6qYPgAfDNfV4YlYrM',authDomain:'yes-card-gacha-rgb.firebaseapp.com',messagingSenderId:'496431023991'},ADMIN='info@rgb-workshop.com',ROOT='https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/hongKongFishing',$=s=>document.querySelector(s),auth=getAuth(initializeApp(FIREBASE_CONFIG));let config;
const fields=[['texts.title','遊戲名稱'],['texts.eyebrow','英文小標'],['texts.areaLabel','地區標籤'],['texts.distanceLabel','距離標籤'],['texts.scoreLabel','分數標籤'],['texts.powerLabel','收魚時機標題'],['texts.hitHint','收魚提示'],['texts.tensionLabel','魚絲張力標題'],['texts.tensionHint','張力提示'],['texts.chooseArea','未選釣區文字'],['texts.areaIntro','選區說明'],['texts.startButton','開始按鈕'],['texts.hitButton','收魚按鈕'],['texts.bagButton','背包按鈕'],['texts.areaButton','選擇釣區按鈕'],['texts.returnButton','回到故事按鈕'],['texts.ready','準備訊息'],['texts.waiting','等待訊息'],['texts.biting','上釣訊息'],['texts.miss','失誤訊息'],['texts.hit','命中訊息'],['texts.lineBroken','斷線訊息'],['texts.tryAgain','重新準備訊息'],['texts.noFish','釣區沒有魚的訊息'],['texts.areaTitle','地區選單標題'],['texts.catchTitle','釣獲標題'],['texts.bagTitle','背包標題'],['texts.bagEmpty','空背包文字'],['settings.backgroundUrl','預設背景圖片網址'],['settings.biteDelayMin','最短上釣時間（毫秒）','number'],['settings.biteDelayMax','最長上釣時間（毫秒）','number'],['settings.needleSpeed','指針速度（越小越易）','number'],['settings.targetSize','中央命中區大小（%）','number']];
function get(path){return path.split('.').reduce((o,k)=>o?.[k],config)}function set(path,v){const a=path.split('.'),k=a.pop(),o=a.reduce((x,y)=>x[y],config);o[k]=v}function input(value,placeholder,type='text',change){const i=document.createElement('input');i.type=type;i.value=value??'';i.placeholder=placeholder;i.oninput=()=>change(type==='number'?+i.value:i.value);return i}
function renderBasic(){const box=$('#basicFields');box.innerHTML='';fields.forEach(([path,label,type='text'])=>{const l=document.createElement('label');l.textContent=label;const i=input(get(path),label,type,v=>set(path,v));i.dataset.path=path;l.append(i);box.append(l)})}
function renderCatalog(){const box=$('#catalog');box.innerHTML='';config.fishCatalog.forEach(f=>{const card=document.createElement('article');card.className='catalog-card';const preview=document.createElement('img');preview.src=f.image||'assets/yellowfin-seabream.png';preview.alt=f.name;const form=document.createElement('div');form.className='catalog-fields';[['name','魚名'],['keywords','搜尋關鍵字'],['image','魚類圖片網址'],['minWeight','最小重量 kg','number'],['maxWeight','最大重量 kg','number'],['points','所得分數','number'],['hits','命中次數','number'],['tensionRate','張力速度','number']].forEach(([k,p,t='text'])=>form.append(input(f[k],p,t,v=>{f[k]=v;if(k==='image')preview.src=v;if(k==='name')preview.alt=v;renderAreas()})));const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='刪除魚類';del.onclick=()=>{config.fishCatalog=config.fishCatalog.filter(x=>x!==f);config.areas.forEach(a=>a.fish=a.fish.filter(x=>x.fishId!==f.id));renderCatalog();renderAreas()};card.append(preview,form,del);box.append(card)})}
function assignmentRow(entry,a){const fish=config.fishCatalog.find(f=>f.id===entry.fishId),row=document.createElement('div');row.className='assignment-row';if(!fish)return row;row.innerHTML=`<img src="${fish.image}" alt=""><b>${fish.name}</b><small>${fish.minWeight}–${fish.maxWeight} kg · ${fish.points} 分 · ${fish.hits} 次</small>`;row.append(input(entry.weight??1,'出現權重','number',v=>entry.weight=v));const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='移除';del.onclick=()=>{a.fish=a.fish.filter(x=>x!==entry);renderAreas()};row.append(del);return row}
function searchBox(a){const wrap=document.createElement('div');wrap.className='fish-search';const q=input('','輸入魚名或關鍵字，例如「斑」');const results=document.createElement('div');results.className='search-results';function search(){const term=q.value.trim().toLowerCase();results.innerHTML='';if(!term)return;config.fishCatalog.filter(f=>`${f.name} ${f.keywords||''}`.toLowerCase().includes(term)&&!a.fish.some(x=>x.fishId===f.id)).slice(0,8).forEach(f=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<img src="${f.image}" alt=""><span><b>${f.name}</b><small>${f.minWeight}–${f.maxWeight} kg · ${f.points} 分</small></span>`;b.onclick=()=>{a.fish.push({fishId:f.id,weight:1});renderAreas()};results.append(b)})}q.oninput=search;wrap.append(q,results);return wrap}
function renderAreas(){const box=$('#areas');box.innerHTML='';config.areas.forEach((a,index)=>{const card=document.createElement('article');card.className='area-card';const title=document.createElement('h3');title.textContent=`釣區 ${index+1}：${a.name}`;const head=document.createElement('div');head.className='fields';head.append(input(a.name,'地區名稱','text',v=>{a.name=v;title.textContent=`釣區 ${index+1}：${v}`}),input(a.description,'地區描述','text',v=>a.description=v),input(a.backgroundUrl,'此區背景圖片網址','text',v=>a.backgroundUrl=v));const preview=document.createElement('div');preview.className='area-preview';preview.style.backgroundImage=`url("${a.backgroundUrl||config.settings.backgroundUrl}")`;const assigned=document.createElement('div');assigned.className='assignments';a.fish.forEach(entry=>assigned.append(assignmentRow(entry,a)));const del=document.createElement('button');del.type='button';del.className='danger';del.textContent='刪除整個釣區';del.onclick=()=>{config.areas=config.areas.filter(x=>x!==a);renderAreas()};card.append(title,head,preview,document.createElement('h4'),assigned,searchBox(a),del);card.querySelector('h4').textContent='此區會出現的魚';box.append(card)})}
async function local(){return(await fetch('config.json',{cache:'no-store'})).json()}async function reload(){const base=await local(),token=await auth.currentUser.getIdToken(),r=await fetch(ROOT,{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const d=await r.json(),p=d.fields?.payload?.stringValue,remote=p?JSON.parse(p):null;config=remote?.version>=3?remote:base}else config=base;config.fishCatalog||=[];renderBasic();renderCatalog();renderAreas()}
async function publish(e){e.preventDefault();config.version=3;const token=await auth.currentUser.getIdToken(),r=await fetch(ROOT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(config)}}})});$('#status').textContent=r.ok?'已成功發佈。':'發佈失敗：'+await r.text()}
$('#loginButton').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){$('#loginMessage').textContent='登入失敗：'+e.message}};$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=reload;$('#editor').onsubmit=publish;
$('#addFish').onclick=()=>{config.fishCatalog.push({id:`fish-${Date.now()}`,name:'新魚類',keywords:'',image:'assets/yellowfin-seabream.png',minWeight:.5,maxWeight:2,points:100,hits:3,tensionRate:.025});renderCatalog();renderAreas()};
$('#addArea').onclick=()=>{config.areas.push({id:`area-${Date.now()}`,name:'新地區',description:'',backgroundUrl:config.settings.backgroundUrl,fish:[]});renderAreas()};
onAuthStateChanged(auth,async u=>{const ok=u?.email?.toLowerCase()===ADMIN&&u.emailVerified;if(u&&!ok){await signOut(auth);$('#loginMessage').textContent='此帳戶沒有管理權限';return}$('#login').hidden=!!ok;$('#editor').hidden=!ok;if(ok){$('#userEmail').textContent=u.email;await reload()}});
