const PROJECT='yes-card-gacha-rgb',ROOT=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/miniGames/hongKongFishing`,$=s=>document.querySelector(s),BAG_KEY='hong-kong-fishing-bag-v1';let config,area,fish,state='idle',score=0,distance=0,hits=0,needle=5,dir=1,raf,biteTimer,bag=[];try{bag=JSON.parse(localStorage.getItem(BAG_KEY)||'[]')}catch{}
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}async function remote(){const r=await fetch(ROOT,{cache:'no-store'});if(!r.ok)return null;const d=await r.json(),p=d.fields?.payload?.stringValue;return p?JSON.parse(p):null}function text(id,v){$(id).textContent=v}function fmt(n){return Number(n).toFixed(1)}function weighted(list){const total=list.reduce((n,x)=>n+Math.max(.01,+x.weight||1),0);let roll=Math.random()*total;return list.find(x=>(roll-=Math.max(.01,+x.weight||1))<=0)||list[0]}
function apply(){const t=config.texts;document.title=t.title;$('#game').style.backgroundImage=`url("${config.settings.backgroundUrl}")`;['title','eyebrow','areaLabel','distanceLabel','scoreLabel','powerLabel','hitHint'].forEach(k=>text('#'+k,t[k]));text('#start',t.startButton);text('#hit',t.hitButton);text('#openBag',t.bagButton);text('#changeArea',t.areaButton);text('#returnStory',t.returnButton);text('#areaTitle',t.areaTitle);text('#catchEyebrow',t.catchEyebrow);text('#catchTitle',t.catchTitle);text('#fishAgain',t.againButton);text('#bagTitle',t.bagTitle);text('#bagEmpty',t.bagEmpty);document.querySelectorAll('[data-close="catchModal"]').forEach(b=>b.textContent=t.closeButton);selectArea(config.areas[0]);renderAreas()}
function selectArea(a){area=a;text('#areaName',a.name);close('areaModal');reset()}function reset(){clearTimeout(biteTimer);cancelAnimationFrame(raf);state='idle';fish=null;distance=0;hits=0;needle=5;text('#distance','—');text('#message','');text('#biteAlert','');$('#rod').className='rod raised';$('#line').className='';$('#start').classList.remove('hidden');$('#hit').classList.add('hidden');$('#powerNeedle').style.top='5%'}
function renderAreas(){const g=$('#areaGrid');g.innerHTML='';config.areas.forEach(a=>{const b=document.createElement('button');b.innerHTML=`<b>${a.name}</b><span>${a.description||''}</span><small>${a.fish.length} 種魚</small>`;b.onclick=()=>selectArea(a);g.append(b)})}function open(id){$('#'+id).classList.remove('hidden')}function close(id){$('#'+id).classList.add('hidden')}
function cast(){if(state!=='idle')return;state='waiting';$('#rod').className='rod cast';$('#line').className='cast';$('#splash').className='on';$('#start').classList.add('hidden');text('#message',config.texts.waiting);const min=+config.settings.biteDelayMin||1200,max=+config.settings.biteDelayMax||2800;biteTimer=setTimeout(bite,min+Math.random()*(max-min))}
function bite(){state='hooked';fish=weighted(area.fish);hits=0;distance=Math.max(3,+fish.hits||3)*1.5;text('#distance',fmt(distance));text('#message',config.texts.biting);text('#biteAlert','！');$('#hit').classList.remove('hidden');animateNeedle()}
function animateNeedle(){if(state!=='hooked')return;needle+=dir*(+config.settings.needleSpeed||1.8);if(needle>=92){needle=92;dir=-1}if(needle<=4){needle=4;dir=1}$('#powerNeedle').style.top=needle+'%';raf=requestAnimationFrame(animateNeedle)}
function strike(){if(state!=='hooked')return;const size=+config.settings.targetSize||16,low=50-size/2,high=50+size/2;if(needle>=low&&needle<=high){hits++;distance=Math.max(0,distance-1.5);text('#message',config.texts.hit);$('#game').classList.add('hit-flash');setTimeout(()=>$('#game').classList.remove('hit-flash'),160);if(hits>=fish.hits||distance<=0)return caught()}else{distance+=.8;text('#message',config.texts.miss)}text('#distance',fmt(distance))}
function caught(){state='caught';cancelAnimationFrame(raf);distance=0;text('#distance','0.0');const weight=+(fish.minWeight+Math.random()*(fish.maxWeight-fish.minWeight)).toFixed(1),points=+fish.points||0;score+=points;text('#score',score);text('#caughtName',fish.name);text('#caughtWeight',weight);text('#caughtPoints',points);text('#fishArt',fish.icon||'🐟');bag.unshift({id:fish.id,name:fish.name,icon:fish.icon||'🐟',weight,points,area:area.name,time:Date.now()});localStorage.setItem(BAG_KEY,JSON.stringify(bag));open('catchModal')}
function renderBag(){const g=$('#bagGrid');g.innerHTML='';bag.forEach(x=>{const a=document.createElement('article');a.innerHTML=`<div class="fish-icon">${x.icon}</div><b>${x.name}</b><p>${x.weight} kg · ${x.points} 分</p><small>${x.area}</small>`;g.append(a)});$('#bagEmpty').hidden=!!bag.length;open('bagModal')}
$('#start').onclick=cast;$('#hit').onclick=strike;$('#openBag').onclick=renderBag;$('#changeArea').onclick=()=>open('areaModal');$('#fishAgain').onclick=()=>{close('catchModal');reset();cast()};$('#returnStory').onclick=()=>window.parent.postMessage({complete:true,score},'*');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{close(b.dataset.close);if(b.dataset.close==='catchModal')reset()});document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state==='hooked'?strike():state==='idle'&&cast()}if(e.key==='Escape'){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));if(state==='caught')reset()}});
(async()=>{const f=await fallback();let r;try{r=await remote()}catch{}config={texts:{...f.texts,...r?.texts},settings:{...f.settings,...r?.settings},areas:r?.areas?.length?r.areas:f.areas};apply()})();
