const PROJECT='yes-card-gacha-rgb',ROOT=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/miniGames/hongKongFishing`,$=s=>document.querySelector(s),BAG_KEY='hong-kong-fishing-bag-v4',PROGRESS_KEY='hong-kong-fishing-progress-v1',CATALOG_VERSION=6;
let config,area=null,fish=null,state='idle',score=0,distance=0,hits=0,needle=5,dir=1,tension=18,raf,biteTimer,bag=[],progress={unlocked:1,completed:{},catches:{}},hostScore=0,hookWeight=0,requiredHits=3,fightLevel=0,currentTargetSize=30,currentNeedleSpeed=.85,missPenalty=22,tensionRelief=15,tensionGrowth=1,pendingAreaClear=false;
const DIFFICULTY_NAMES=['非常容易','容易','普通','困難','專家'];
const GLOBAL_DIFFICULTY=[{target:1,speed:1,hits:0,miss:1,relief:1,start:1,growth:1},{target:.9,speed:1.12,hits:1,miss:1.12,relief:.9,start:1.08,growth:1.12},{target:.78,speed:1.28,hits:2,miss:1.28,relief:.78,start:1.18,growth:1.28},{target:.66,speed:1.48,hits:3,miss:1.48,relief:.66,start:1.32,growth:1.48},{target:.55,speed:1.75,hits:4,miss:1.75,relief:.55,start:1.48,growth:1.75}];
const AREA_DIFFICULTY=[{target:1,speed:1,hits:0,miss:1,relief:1,start:1,growth:1},{target:.95,speed:1.06,hits:0,miss:1.05,relief:.95,start:1.04,growth:1.06},{target:.88,speed:1.14,hits:1,miss:1.12,relief:.9,start:1.08,growth:1.14},{target:.8,speed:1.24,hits:1,miss:1.22,relief:.82,start:1.15,growth:1.24},{target:.72,speed:1.36,hits:2,miss:1.35,relief:.72,start:1.25,growth:1.36}];
const imageCache=new Map();let preloadDone=0,preloadTotal=0;
const embedded=window.parent!==window;
if(!embedded){try{bag=JSON.parse(localStorage.getItem(BAG_KEY)||'[]').filter(x=>x.catalogVersion===CATALOG_VERSION)}catch{}try{progress={...progress,...JSON.parse(localStorage.getItem(PROGRESS_KEY)||'{}')}}catch{}}
function incomingHostScore(){const raw=new URLSearchParams(location.search).get('score');if(raw!==null&&raw!==''&&Number.isFinite(+raw))return +raw;if(Number.isFinite(window.__islandScore))return +window.__islandScore;return 0}
function persistBag(){if(embedded)reportToParent(false);else localStorage.setItem(BAG_KEY,JSON.stringify(bag))}
function persistProgress(){if(embedded)reportToParent(false);else localStorage.setItem(PROGRESS_KEY,JSON.stringify(progress))}
function reportToParent(done){if(!embedded)return;window.parent.postMessage({type:'island-stats',set:{score:hostScore+score,fishingBag:bag,fishingProgress:progress},complete:!!done},'*')}
window.addEventListener('message',e=>{const d=e.data;if(!d||typeof d!=='object'||d.type!=='island-stats')return;if(d.request==='dump'){reportToParent(false);return}if(Number.isFinite(+d.score)&&state==='idle'){window.__islandScore=+d.score;hostScore=+d.score}if(Array.isArray(d.fishingBag)){bag=d.fishingBag.filter(x=>x.catalogVersion===CATALOG_VERSION)}if(d.fishingProgress&&typeof d.fishingProgress==='object'){progress={...progress,...d.fishingProgress};renderAreas();renderObjectives()}});
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}
async function remote(){const r=await fetch(ROOT,{cache:'no-store'});if(!r.ok)return null;const d=await r.json(),p=d.fields?.payload?.stringValue;return p?JSON.parse(p):null}
function text(id,v){$(id).textContent=v??''} function fmt(n){return Number(n).toFixed(1)}
function assetFor(f){return f?.id?`assets/fish/${f.id}.png`:(f?.image||'assets/yellowfin-seabream.png')}
function preloadImage(src,priority=false){if(imageCache.has(src))return imageCache.get(src);const job=new Promise(resolve=>{const img=new Image();if(priority)img.fetchPriority='high';img.onload=img.onerror=()=>resolve(src);img.src=src});imageCache.set(src,job);return job}
function updatePreload(){if(!preloadTotal)return;const pct=Math.round(preloadDone/preloadTotal*100);$('#preloadBar').style.width=pct+'%';text('#preloadText',preloadDone>=preloadTotal?'30 種魚圖已準備好':`正在準備魚類圖鑑 ${preloadDone} / ${preloadTotal}`)}
async function preloadFishList(list,priority=false){const urls=[...new Set(list.map(assetFor))];await Promise.all(urls.map(async src=>{const known=imageCache.has(src);await preloadImage(src,priority);if(!known){preloadDone++;updatePreload()}}))}
async function backgroundPreload(){preloadTotal=config.fishCatalog.length;updatePreload();const queue=[...config.fishCatalog];for(let i=0;i<queue.length;i+=3){await preloadFishList(queue.slice(i,i+3));await new Promise(resolve=>window.requestIdleCallback?requestIdleCallback(resolve,{timeout:120}):setTimeout(resolve,60))}}
function fishForArea(a){return (a.fish||[]).map(entry=>{if(entry.name)return entry;const base=(config.fishCatalog||[]).find(f=>f.id===entry.fishId);return base?{...base,...entry,id:base.id}:null}).filter(Boolean)}
function fishById(id){return config.fishCatalog.find(f=>f.id===id)}
function areaIndex(a){return config.areas.findIndex(x=>x.id===a.id)}
function isUnlocked(a){return areaIndex(a)<Math.max(1,+progress.unlocked||1)}
function catchCount(a,fishId){return +progress.catches?.[a.id]?.[fishId]||0}
function objectivesFor(a){return (a.objectives||[]).slice(0,3).map(o=>({...o,fish:fishById(o.fishId),current:catchCount(a,o.fishId)})).filter(o=>o.fish)}
function areaComplete(a){const list=objectivesFor(a);return list.length===3&&list.every(o=>o.current>=o.count)}
function renderObjectives(){if(!area){$('#questPanel').classList.add('hidden');return}const list=objectivesFor(area),box=$('#questList');box.innerHTML='';list.forEach(o=>{const p=document.createElement('p');p.className=o.current>=o.count?'done':'';p.innerHTML=`<span>${o.current>=o.count?'✓':'○'} ${o.fish.name}</span><b>${Math.min(o.current,o.count)} / ${o.count}</b>`;box.append(p)});text('#questTitle',progress.completed?.[area.id]?'本區目標已完成':'本區通關目標');text('#questReward',progress.completed?.[area.id]?'可自由在本區繼續釣魚':`完成三項目標：+${+config.settings.areaClearReward||200} 分`);$('#questPanel').classList.remove('hidden')}
function recordCatch(a,f){progress.catches[a.id]||={};progress.catches[a.id][f.id]=catchCount(a,f.id)+1;let cleared=false;if(!progress.completed[a.id]&&areaComplete(a)){const reward=+config.settings.areaClearReward||200;progress.completed[a.id]=true;progress.unlocked=Math.min(config.areas.length,Math.max(+progress.unlocked||1,areaIndex(a)+2));score+=reward;pendingAreaClear=true;cleared=true;text('#score',hostScore+score)}persistProgress();renderObjectives();renderAreas();return cleared}
function weighted(list){const total=list.reduce((n,x)=>n+Math.max(.01,+x.weight||1),0);let roll=Math.random()*total;return list.find(x=>(roll-=Math.max(.01,+x.weight||1))<=0)||list[0]}
function difficultyLevel(value,fallback=1){return Math.max(1,Math.min(5,Math.round(+value||fallback)))}
function difficultyFor(f,w){const level=w>=8?3:w>=4?2:w>=1.5?1:0,globalLevel=difficultyLevel(config.settings.difficultyLevel,3),areaLevel=difficultyLevel(area?.difficultyLevel,3),g=GLOBAL_DIFFICULTY[globalLevel-1],a=AREA_DIFFICULTY[areaLevel-1],baseTarget=[30,24,18,13][level],baseSpeed=(+config.settings.needleSpeed||.85)*[1,1.18,1.45,1.75][level];return {level,label:['小魚','中型魚','大魚','巨物'][level],stars:'★'.repeat(level+1)+'☆'.repeat(3-level),globalLevel,areaLevel,globalName:DIFFICULTY_NAMES[globalLevel-1],areaName:DIFFICULTY_NAMES[areaLevel-1],target:Math.max(7,Math.round(baseTarget*g.target*a.target)),speed:baseSpeed*g.speed*a.speed,extraHits:[0,1,2,3][level]+g.hits+a.hits,miss:Math.round([22,27,33,40][level]*g.miss*a.miss),relief:Math.max(4,Math.round([15,13,10,7][level]*g.relief*a.relief)),startTension:Math.min(60,Math.round([20,24,29,35][level]*g.start*a.start)),growth:g.growth*a.growth}}
function applyFightDifficulty(d){fightLevel=d.level;currentTargetSize=d.target;currentNeedleSpeed=d.speed;missPenalty=d.miss;tensionRelief=d.relief;tensionGrowth=d.growth||1;const target=$('.target');target.style.height=currentTargetSize+'%';target.style.top=(50-currentTargetSize/2)+'%'}
function apply(){const t=config.texts;document.title=t.title;$('#game').style.backgroundImage=`url("${config.settings.backgroundUrl}")`;['title','eyebrow','areaLabel','distanceLabel','scoreLabel','powerLabel','hitHint','tensionLabel','tensionHint','areaIntro'].forEach(k=>text('#'+k,t[k]));text('#start',t.startButton||'拋竿開始');text('#hit','收魚絲');text('#openBag',t.bagButton);text('#changeArea',t.areaButton);text('#returnStory',t.returnButton);text('#areaTitle',t.areaTitle);text('#catchEyebrow',t.catchEyebrow);text('#catchTitle',t.catchTitle);text('#fishAgain',t.againButton);text('#bagTitle',t.bagTitle);text('#bagEmpty',t.bagEmpty);const size=+config.settings.targetSize||30;$('.target').style.cssText=`height:${size}%;top:${50-size/2}%`;document.querySelectorAll('[data-close="catchModal"]').forEach(b=>b.textContent=t.closeButton);hostScore=incomingHostScore();renderAreas();reset();text('#areaName',t.chooseArea);text('#score',hostScore+score)}
function selectArea(a){if(!isUnlocked(a))return;area=a;text('#areaName',a.name);$('#game').style.backgroundImage=`url("${a.backgroundUrl||config.settings.backgroundUrl}")`;$('#start').disabled=false;close('areaModal');reset();renderObjectives();text('#message','正在準備這個釣點的魚群…');preloadFishList(fishForArea(a),true).then(()=>text('#message',config.texts.ready))}
function reset(){clearTimeout(biteTimer);cancelAnimationFrame(raf);state='idle';fish=null;hookWeight=0;distance=0;hits=0;requiredHits=3;fightLevel=0;needle=5;dir=1;tension=18;currentTargetSize=+config.settings.targetSize||30;currentNeedleSpeed=+config.settings.needleSpeed||.85;missPenalty=22;tensionRelief=15;tensionGrowth=1;applyFightDifficulty({level:0,target:currentTargetSize,speed:currentNeedleSpeed,miss:22,relief:15,growth:1});text('#distance','—');text('#biteAlert','');$('#rod').className='rod raised';$('#line').className='';$('#start').classList.remove('hidden');$('#hit').classList.add('hidden');$('#powerNeedle').style.top='5%';updateTension();if(!area)$('#start').disabled=true}
function renderAreas(){const g=$('#areaGrid');if(!g)return;g.innerHTML='';config.areas.forEach((a,i)=>{const fishes=fishForArea(a),b=document.createElement('button'),areaDifficulty=DIFFICULTY_NAMES[difficultyLevel(a.difficultyLevel,3)-1],unlocked=isUnlocked(a),done=!!progress.completed?.[a.id],objectives=objectivesFor(a);b.style.backgroundImage=`linear-gradient(145deg,#092129e6,#071c22c7),url("${a.backgroundUrl||config.settings.backgroundUrl}")`;b.className=!unlocked?'locked':done?'completed':'';b.disabled=!unlocked;b.innerHTML=`<span class="area-no">0${i+1}</span><b>${a.name}</b><span>${a.description||''}</span><small>地區難度：${areaDifficulty}｜${fishes.length} 種魚類</small><small class="objective-mini">${objectives.map(o=>`<i class="${o.current>=o.count?'done':''}">${o.current>=o.count?'✓':'○'} ${o.fish.name} ${Math.min(o.current,o.count)}/${o.count}</i>`).join('')}</small><span class="lock-label">${!unlocked?'🔒 完成上一區後解鎖':done?'✓ 已通關・可自由釣魚':'完成三項目標獲得 200 分'}</span>`;b.onclick=()=>selectArea(a);g.append(b)})}
function open(id){$('#'+id).classList.remove('hidden')} function close(id){$('#'+id).classList.add('hidden')}
function cast(){if(state!=='idle'||!area)return;state='waiting';$('#rod').className='rod cast';$('#line').className='cast';$('#splash').className='on';$('#start').classList.add('hidden');text('#message',config.texts.waiting);const min=+config.settings.biteDelayMin||900,max=+config.settings.biteDelayMax||1900;biteTimer=setTimeout(bite,min+Math.random()*(max-min))}
function bite(){state='hooked';fish=weighted(fishForArea(area));if(!fish){reset();text('#message',config.texts.noFish||'這個釣區尚未設定魚種。');return}hookWeight=+(+fish.minWeight+Math.random()*(+fish.maxWeight-+fish.minWeight)).toFixed(1);const d=difficultyFor(fish,hookWeight);applyFightDifficulty(d);hits=0;requiredHits=Math.max(2,+fish.hits||3)+d.extraHits;tension=d.startTension;distance=requiredHits*1.25;text('#distance',fmt(distance));text('#message',`${config.texts.biting} ${d.label}・${d.stars}｜整體 ${d.globalName}・本區 ${d.areaName}`);text('#biteAlert',`${d.stars} FISH ON`);$('#hit').classList.remove('hidden');updateTension();animateNeedle()}
function animateNeedle(){if(state!=='hooked')return;needle+=dir*currentNeedleSpeed;if(needle>=94){needle=94;dir=-1}if(needle<=3){needle=3;dir=1}tension=Math.min(100,tension+(+fish.tensionRate||.025)*(1+fightLevel*.28)*tensionGrowth);$('#powerNeedle').style.top=needle+'%';updateTension();if(tension>=100)return lineBreak();raf=requestAnimationFrame(animateNeedle)}
function updateTension(){$('#tensionFill').style.height=Math.max(0,Math.min(100,tension))+'%';$('#tensionFill').classList.toggle('danger',tension>=72)}
function strike(){if(state!=='hooked')return;const low=50-currentTargetSize/2,high=50+currentTargetSize/2;if(needle>=low&&needle<=high){hits++;distance=Math.max(0,distance-1.25);tension=Math.max(8,tension-tensionRelief);text('#message',`${config.texts.hit} ${hits} / ${requiredHits}`);$('#game').classList.add('hit-flash');setTimeout(()=>$('#game').classList.remove('hit-flash'),160);if(hits>=requiredHits||distance<=.05)return caught()}else{distance+=.35+.15*fightLevel;tension+=missPenalty;text('#message',config.texts.miss);if(tension>=100)return lineBreak()}text('#distance',fmt(distance));updateTension()}
function lineBreak(){state='broken';cancelAnimationFrame(raf);text('#message',config.texts.lineBroken);text('#biteAlert','LINE BREAK');$('#line').className='broken';$('#hit').classList.add('hidden');setTimeout(()=>{reset();text('#message',config.texts.tryAgain)},1300)}
function caught(){state='caught';cancelAnimationFrame(raf);distance=0;text('#distance','0.0');const weight=hookWeight;recordCatch(area,fish);text('#caughtName',fish.name);text('#caughtInfo',[fish.enName,fish.habitat,['小魚','中型魚','大魚','巨物'][fightLevel]].filter(Boolean).join('｜'));text('#caughtWeight',weight);text('#caughtPoints','魚獲不計分・通關才獲得 200 分');const image=assetFor(fish);$('#fishArt').src=image;bag.unshift({id:fish.id,name:fish.name,enName:fish.enName,image,weight,points:0,area:area.name,time:Date.now(),catalogVersion:CATALOG_VERSION});persistBag();open('catchModal')}
function renderBag(){const g=$('#bagGrid');g.innerHTML='';let unlocked=0;config.fishCatalog.forEach(f=>{const catches=bag.filter(x=>x.id===f.id),latest=catches[0],a=document.createElement('article');if(!latest)a.className='locked';else unlocked++;a.innerHTML=`<img src="${assetFor(f)}" alt="${f.name}"><b>${f.name}</b><small>${f.enName||''}</small><p>${latest?`${latest.weight} kg · ${latest.area}`:'尚未釣獲'}</p>${catches.length>1?`<em>捕獲 ${catches.length} 次</em>`:''}`;g.append(a)});text('#bagEmpty',`圖鑑進度 ${unlocked} / ${config.fishCatalog.length}`);$('#bagEmpty').hidden=false;open('bagModal')}
function showAreaComplete(){pendingAreaClear=false;const reward=+config.settings.areaClearReward||200,next=config.areas[areaIndex(area)+1];text('#areaCompleteTitle',`${area.name}通關！`);text('#areaReward',`+${reward} 分`);text('#areaCompleteText',next?`已解鎖下一個釣區：${next.name}。你亦可繼續在已解鎖地區自由釣魚。`:'全部釣區已完成！所有地區都可以自由釣魚。');open('areaCompleteModal')}
function afterCatch(autoCast=false){close('catchModal');reset();if(pendingAreaClear)return showAreaComplete();if(autoCast)cast()}
$('#enterGame').onclick=()=>{close('startScreen');open('areaModal')};$('#start').onclick=cast;$('#hit').onclick=strike;$('#openBag').onclick=renderBag;$('#changeArea').onclick=()=>{renderAreas();open('areaModal')};$('#fishAgain').onclick=()=>afterCatch(true);$('#returnStory').onclick=()=>reportToParent(true);$('#continueFishing').onclick=()=>{close('areaCompleteModal');reset()};$('#chooseUnlockedArea').onclick=()=>{close('areaCompleteModal');renderAreas();open('areaModal')};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='areaModal'&&!area)return;close(b.dataset.close);if(b.dataset.close==='catchModal'){reset();if(pendingAreaClear)showAreaComplete()}});
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state==='hooked'?strike():state==='idle'&&area&&cast()}if(e.key==='Escape'&&area){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));if(state==='caught'){reset();if(pendingAreaClear)showAreaComplete()}}});
(async()=>{const f=await fallback();let r;try{r=await remote()}catch{}const current=r?.version>=f.version?r:null;config={version:f.version,texts:{...f.texts,...current?.texts},settings:{...f.settings,...current?.settings},fishCatalog:current?.fishCatalog?.length?current.fishCatalog:f.fishCatalog,areas:current?.areas?.length?current.areas:f.areas};progress.unlocked=Math.max(1,Math.min(config.areas.length,+progress.unlocked||1));progress.completed=progress.completed||{};progress.catches=progress.catches||{};config.texts.hitButton='收魚絲';apply();backgroundPreload()})();
