const PROJECT='yes-card-gacha-rgb',ROOT=`https://firestore.googleapis.com/v1/projects/${PROJECT}/databases/(default)/documents/miniGames/hongKongFishing`,$=s=>document.querySelector(s),BAG_KEY='hong-kong-fishing-bag-v2';
let config,area=null,fish=null,state='idle',score=0,distance=0,hits=0,needle=5,dir=1,tension=18,raf,biteTimer,bag=[];
try{bag=JSON.parse(localStorage.getItem(BAG_KEY)||'[]')}catch{}
async function fallback(){return(await fetch('config.json',{cache:'no-store'})).json()}
async function remote(){const r=await fetch(ROOT,{cache:'no-store'});if(!r.ok)return null;const d=await r.json(),p=d.fields?.payload?.stringValue;return p?JSON.parse(p):null}
function text(id,v){$(id).textContent=v||''} function fmt(n){return Number(n).toFixed(1)}
function assetFor(f){if(f.image)return f.image;return f.name?.includes('斑')?'assets/orange-spotted-grouper.png':f.name?.includes('烏頭')?'assets/grey-mullet.png':f.name?.includes('鱸')?'assets/japanese-seabass.png':'assets/yellowfin-seabream.png'}
function weighted(list){const total=list.reduce((n,x)=>n+Math.max(.01,+x.weight||1),0);let roll=Math.random()*total;return list.find(x=>(roll-=Math.max(.01,+x.weight||1))<=0)||list[0]}
function apply(){const t=config.texts;document.title=t.title;$('#game').style.backgroundImage=`url("${config.settings.backgroundUrl}")`;['title','eyebrow','areaLabel','distanceLabel','scoreLabel','powerLabel','hitHint','tensionLabel','tensionHint','areaIntro'].forEach(k=>text('#'+k,t[k]));text('#start',t.startButton);text('#hit',t.hitButton);text('#openBag',t.bagButton);text('#changeArea',t.areaButton);text('#returnStory',t.returnButton);text('#areaTitle',t.areaTitle);text('#catchEyebrow',t.catchEyebrow);text('#catchTitle',t.catchTitle);text('#fishAgain',t.againButton);text('#bagTitle',t.bagTitle);text('#bagEmpty',t.bagEmpty);const size=+config.settings.targetSize||30;$('.target').style.cssText=`height:${size}%;top:${50-size/2}%`;document.querySelectorAll('[data-close="catchModal"]').forEach(b=>b.textContent=t.closeButton);renderAreas();reset();text('#areaName',t.chooseArea);open('areaModal')}
function selectArea(a){area=a;text('#areaName',a.name);$('#start').disabled=false;close('areaModal');reset();text('#message',config.texts.ready)}
function reset(){clearTimeout(biteTimer);cancelAnimationFrame(raf);state='idle';fish=null;distance=0;hits=0;needle=5;dir=1;tension=18;text('#distance','—');text('#biteAlert','');$('#rod').className='rod raised';$('#line').className='';$('#start').classList.remove('hidden');$('#hit').classList.add('hidden');$('#powerNeedle').style.top='5%';updateTension();if(!area)$('#start').disabled=true}
function renderAreas(){const g=$('#areaGrid');g.innerHTML='';config.areas.forEach((a,i)=>{const b=document.createElement('button');b.innerHTML=`<span class="area-no">0${i+1}</span><b>${a.name}</b><span>${a.description||''}</span><small>${a.fish.map(x=>x.name).join(' · ')}</small>`;b.onclick=()=>selectArea(a);g.append(b)})}
function open(id){$('#'+id).classList.remove('hidden')} function close(id){$('#'+id).classList.add('hidden')}
function cast(){if(state!=='idle'||!area)return;state='waiting';$('#rod').className='rod cast';$('#line').className='cast';$('#splash').className='on';$('#start').classList.add('hidden');text('#message',config.texts.waiting);const min=+config.settings.biteDelayMin||900,max=+config.settings.biteDelayMax||1900;biteTimer=setTimeout(bite,min+Math.random()*(max-min))}
function bite(){state='hooked';fish=weighted(area.fish);hits=0;tension=22;distance=Math.max(3,+fish.hits||3)*1.25;text('#distance',fmt(distance));text('#message',config.texts.biting);text('#biteAlert','FISH ON');$('#hit').classList.remove('hidden');updateTension();animateNeedle()}
function animateNeedle(){if(state!=='hooked')return;needle+=dir*(+config.settings.needleSpeed||.85);if(needle>=94){needle=94;dir=-1}if(needle<=3){needle=3;dir=1}tension=Math.min(100,tension+(+fish.tensionRate||.025));$('#powerNeedle').style.top=needle+'%';updateTension();if(tension>=100)return lineBreak();raf=requestAnimationFrame(animateNeedle)}
function updateTension(){$('#tensionFill').style.height=Math.max(0,Math.min(100,tension))+'%';$('#tensionFill').classList.toggle('danger',tension>=72)}
function strike(){if(state!=='hooked')return;const size=+config.settings.targetSize||30,low=50-size/2,high=50+size/2;if(needle>=low&&needle<=high){hits++;distance=Math.max(0,distance-(Math.max(3,+fish.hits||3)*1.25)/(+fish.hits||3));tension=Math.max(8,tension-15);text('#message',config.texts.hit);$('#game').classList.add('hit-flash');setTimeout(()=>$('#game').classList.remove('hit-flash'),160);if(hits>=fish.hits||distance<=.05)return caught()}else{distance+=.35;tension+=22;text('#message',config.texts.miss);if(tension>=100)return lineBreak()}text('#distance',fmt(distance));updateTension()}
function lineBreak(){state='broken';cancelAnimationFrame(raf);text('#message',config.texts.lineBroken);text('#biteAlert','LINE BREAK');$('#line').className='broken';$('#hit').classList.add('hidden');setTimeout(()=>{reset();text('#message',config.texts.tryAgain)},1300)}
function caught(){state='caught';cancelAnimationFrame(raf);distance=0;text('#distance','0.0');const weight=+(+fish.minWeight+Math.random()*(+fish.maxWeight-+fish.minWeight)).toFixed(1),points=+fish.points||0;score+=points;text('#score',score);text('#caughtName',fish.name);text('#caughtWeight',weight);text('#caughtPoints',points);const image=assetFor(fish);$('#fishArt').src=image;bag.unshift({id:fish.id,name:fish.name,image,weight,points,area:area.name,time:Date.now()});localStorage.setItem(BAG_KEY,JSON.stringify(bag));open('catchModal')}
function renderBag(){const g=$('#bagGrid');g.innerHTML='';bag.forEach(x=>{const a=document.createElement('article');a.innerHTML=`<img src="${x.image||'assets/yellowfin-seabream.png'}" alt="${x.name}"><b>${x.name}</b><p>${x.weight} kg · ${x.points} 分</p><small>${x.area}</small>`;g.append(a)});$('#bagEmpty').hidden=!!bag.length;open('bagModal')}
$('#start').onclick=cast;$('#hit').onclick=strike;$('#openBag').onclick=renderBag;$('#changeArea').onclick=()=>open('areaModal');$('#fishAgain').onclick=()=>{close('catchModal');reset();cast()};$('#returnStory').onclick=()=>window.parent.postMessage({complete:true,score},'*');
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(b.dataset.close==='areaModal'&&!area)return;close(b.dataset.close);if(b.dataset.close==='catchModal')reset()});
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();state==='hooked'?strike():state==='idle'&&area&&cast()}if(e.key==='Escape'&&area){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));if(state==='caught')reset()}});
(async()=>{const f=await fallback();let r;try{r=await remote()}catch{}config={texts:{...f.texts,...r?.texts},settings:{...f.settings,...r?.settings},areas:r?.areas?.length?r.areas:f.areas};apply()})();
