const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
 const root=path.resolve(__dirname,'..',native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
 const context=await browser.newContext({viewport:native?{width:960,height:540}:{width:1280,height:720},serviceWorkers:'block'}),errors=[],missing=[];
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='www.youtube-nocookie.com')return route.fulfill({contentType:'text/html',body:'<body style="background:#102c3b;color:white;display:grid;place-items:center;font:20px sans-serif">YouTube player</body>'});if(u.href.startsWith('https://hkrgb.github.io/island-journey-visual-novel/')){const rel=u.pathname.split('/island-journey-visual-novel/')[1]||'index.html';return route.fulfill({path:path.resolve(__dirname,'../../../tmp/island-journey-visual-novel/output',rel)});}if(u.hostname==='firestore.googleapis.com')return route.fulfill({json:{fields:{payload:{stringValue:fs.readFileSync(path.resolve(__dirname,u.pathname.includes('mv1wlsxc')?'../../../tmp/birthday-story.json':'../../../tmp/star-story.json'),'utf8').replace(/^\uFEFF/,'')}}}});if(u.hostname==='raw.githubusercontent.com'&&u.pathname.endsWith('/game-core.js'))return route.fulfill({path:path.resolve(__dirname,'../../../tmp/novel-core-reference.js'),contentType:'text/javascript'});if(u.hostname==='raw.githubusercontent.com')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#245566"/></svg>'});if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}await route.fulfill({path:f,contentType:({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});


 const p=await context.newPage();const tapDialogue=async fr=>{const b=await(await fr.frameElement()).boundingBox();const point=await fr.evaluate(()=>{const el=document.querySelector('#dialogue'),r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:innerWidth,h:innerHeight};});await p.mouse.click(b.x+point.x*b.width/point.w,b.y+point.y*b.height/point.h);};p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');
 await p.evaluate(()=>{chooseArea(cfg.areas[0]);showIslandHub();showTheatre();});await p.click('#theatreNext');assert.equal(await p.locator('.theatrePoster>img').getAttribute('alt'),'給爸爸的生日禮物');await p.click('#theatreLock');assert(await p.getByRole('button',{name:'扣除 30 個愛心',exact:true}).isDisabled());assert.equal(await p.getByRole('button',{name:'交出 1 條白點泥鯭',exact:true}).count(),0);
 await p.evaluate(()=>{save.economyEvents=[];for(let i=0;i<10;i++){transact({type:'litter',catchId:'test-'+i,item:{id:'litter-1',name:'海洋垃圾',image:'test.png'}});const w=wallet(),key=[...w.instances.keys()].at(-1);transact({type:'recycle',key,owner:w.instanceOwners.get(key),instance:true});}showTheatre();});assert.equal(await p.evaluate(()=>wallet().hearts),30);await p.locator('.theatrePoster>img').evaluate(x=>x.decode());await p.screenshot({path:path.resolve(__dirname,'../../../tmp/birthday-shelf-'+(native?'app':'web')+'.png')});
 await p.click('#theatrePlay');await p.getByRole('button',{name:'扣除 30 個愛心',exact:true}).click();await p.getByRole('button',{name:'返回選擇',exact:true}).click();assert.equal(await p.evaluate(()=>wallet().hearts),30);await p.getByRole('button',{name:'扣除 30 個愛心',exact:true}).click();const began=Date.now();await p.getByRole('button',{name:'確認扣除並播放',exact:true}).click();assert.equal(await p.evaluate(()=>wallet().hearts),0);assert(await p.evaluate(()=>wallet().stories.has('dad-birthday')));assert.equal(await p.locator('#theatrePlayer iframe').getAttribute('src'),null);
 await p.waitForFunction(()=>theatreSession?.ready,{},{timeout:60000});assert(Date.now()-began>=2900);const frame=await(await p.locator('#theatrePlayer iframe').elementHandle()).contentFrame();await frame.waitForFunction(()=>document.querySelector('#reader.active')&&!cardBusy&&!typing);
 assert.equal(await frame.evaluate(()=>GAME_ID),'給爸爸的生日禮物-mv1wlsxc');assert.equal(await frame.evaluate(()=>STORY.length),63);
 await p.evaluate(()=>dispatchEvent(new MessageEvent('message',{origin:TheatreStory.origin,source:theatreSession.frame.contentWindow,data:{channel:'island-theatre',type:'complete',game:'拋海星的人-musby6ef',session:theatreSession.token}})));assert.equal(await p.evaluate(()=>wallet().storyRewards.size),0);
 await frame.evaluate(()=>{state.i=STORY.length-1;render(false,true);});await frame.waitForFunction(()=>!typing&&!cardBusy);await tapDialogue(frame);await p.waitForFunction(()=>wallet().storyRewards.has('dad-birthday'),{},{timeout:8000});assert.equal(await p.locator('#theatrePlayer').count(),0);assert.equal(await p.locator('.theatreRewards img').count(),1);assert.equal(await p.locator('.theatreRewards figcaption').innerText(),'酒瓶（生日禮物）');await p.locator('.theatreRewards img').evaluate(x=>x.decode());await p.screenshot({path:path.resolve(__dirname,'../../../tmp/birthday-reward-'+(native?'app':'web')+'.png')});
 assert.equal(await p.evaluate(()=>[...wallet().instances.values()].filter(x=>x.id==='birthday-flask').length),1);assert.equal(await p.evaluate(()=>bookshopData().toys.some(x=>x.id==='birthday-flask')),false);await p.getByRole('button',{name:'查看物件',exact:true}).click();assert((await p.locator('#personalContent').innerText()).includes('酒瓶（生日禮物）'));
 await p.evaluate(()=>{showTheatre();playTheatre();});await p.waitForFunction(()=>theatreSession?.ready);const replay=await(await p.locator('#theatrePlayer iframe').elementHandle()).contentFrame();await replay.waitForFunction(()=>document.querySelector('#reader.active')&&!cardBusy&&!typing);await replay.evaluate(()=>{state.i=STORY.length-1;render(false,true);});await replay.waitForFunction(()=>!typing&&!cardBusy);await tapDialogue(replay);await p.waitForFunction(()=>!document.querySelector('#theatrePlayer'));assert.equal(await p.evaluate(()=>wallet().hearts),0);assert.equal(await p.evaluate(()=>wallet().instances.size),1);
 await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);assert(await p.evaluate(()=>wallet().stories.has('dad-birthday')));assert.equal(await p.evaluate(()=>wallet().instances.size),1);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' birthday selection, insufficient hearts, payment cancel, 30-heart deduction, actual story ending, origin/session/game validation, single reward, replay and persistence');await context.close();
 }}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

