const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(!process.env.LIVE){await page.route('https://www.gstatic.com/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());}
 await page.goto(process.env.GAME_URL||'http://127.0.0.1:8765/mini-game/hong-kong-fishing/');await page.waitForSelector('#skipFullscreen');await page.click('#skipFullscreen');await page.waitForFunction(()=>!cloudLoading);
 await page.evaluate(()=>{showIslandHub();chooseArea(cfg.areas[0]);});
 const speeds=await page.evaluate(async()=>{const result=[];tickerIndex=0;for(let i=0;i<3;i++){updateTicker();await new Promise(requestAnimationFrame);const p=document.querySelector('#tickerText'),a=p.getAnimations()[0];a.pause();a.currentTime=1000;const x1=new DOMMatrix(getComputedStyle(p).transform).m41;a.currentTime=2000;const x2=new DOMMatrix(getComputedStyle(p).transform).m41;result.push({title:document.querySelector('#tickerTitle').textContent,speed:x1-x2,duration:a.effect.getTiming().duration});}return result;});
 assert.deepEqual(speeds.map(v=>v.title),['天氣消息','魚類小百科','旅遊資訊']);for(const v of speeds)assert(Math.abs(v.speed-45)<.05,JSON.stringify(v));assert(new Set(speeds.map(v=>v.duration)).size>1);
 await page.click('#returnDirectory');await page.click('#hubBooks');assert.equal(await page.locator('#bookshopHub button').count(),3);assert.equal(await page.locator('#bookshopHub h1,#bookshopHub small,#bookCollection').count(),0);
 const boxes=await page.locator('#bookshopHub button').evaluateAll(nodes=>nodes.map(n=>({x:n.offsetLeft,y:n.offsetTop,width:n.offsetWidth})));assert(boxes.every(b=>b.x===boxes[0].x));assert(boxes[0].y<boxes[1].y&&boxes[1].y<boxes[2].y);
 for(const [period,file] of [['morning','bookshop-morning.png'],['noon','bookshop-bg.jpg'],['night','bookshop-night.png']]){await page.evaluate(period=>{backgroundPeriodOverride=period;updateQuickHud();},period);assert.match(await page.locator('#islandBackdrop').getAttribute('style'),new RegExp(file.replace('.','\\.')));await page.evaluate(()=>new Promise((resolve,reject)=>{const img=new Image();img.onload=resolve;img.onerror=reject;img.src=document.querySelector('#islandBackdrop').dataset.picture;}));if(process.env.SHOTS){fs.mkdirSync(process.env.SHOTS,{recursive:true});await page.screenshot({path:process.env.SHOTS+'/bookshop-'+period+'.png'});}}
 await page.click('#recommendBooks');assert.equal(await page.getByRole('button',{name:'返回書店',exact:true}).count(),0);assert(await page.locator('.bookCopy p').first().evaluate(n=>parseFloat(getComputedStyle(n).fontSize))>=27);assert.match(await page.locator('.bookDetailDialog').evaluate(n=>getComputedStyle(n).backgroundImage),/0\.96/);
 if(process.env.SHOTS)await page.screenshot({path:process.env.SHOTS+'/book-info.png'});
 await page.click('#bookMediaTab');assert.equal(await page.locator('.bookVideos iframe').count(),1);assert.match(await page.locator('.bookVideos iframe').getAttribute('src'),/x0CkI9us3lY/);assert(await page.getByRole('button',{name:'上一頁',exact:true}).isDisabled());
 await page.getByRole('button',{name:'下一頁',exact:true}).click();assert.equal(await page.locator('.bookVideos iframe').count(),1);assert.match(await page.locator('.bookVideos iframe').getAttribute('src'),/a7WQss1TqI0/);assert(await page.getByRole('button',{name:'下一頁',exact:true}).isDisabled());assert.equal(await page.getByRole('button',{name:'返回書店',exact:true}).count(),0);
 if(process.env.SHOTS)await page.screenshot({path:process.env.SHOTS+'/book-video.png'});await page.setViewportSize({width:844,height:390});if(process.env.SHOTS)await page.screenshot({path:process.env.SHOTS+'/book-video-mobile.png'});const box=await page.locator('.bookDetailDialog').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=845&&box.y+box.height<=391);await page.click('#closeModal');assert.equal(await page.locator('#bookshopHub button:visible').count(),3);assert.deepEqual(errors,[]);
 console.log('PASS: all news categories move at 45 artboard px/s, variable travel duration, left buttons, three period images, opaque readable book panel, one video per page, close-to-bookshop, mobile bounds');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
