const {test}=require('node:test'),assert=require('node:assert/strict');require('../sport/economy-core.js');const E=globalThis.CoastEconomy;
const event=(seq,type,data={})=>({id:String(seq),seq,type,...data});
const item={id:'yoyo',name:'搖搖',image:'yoyo.png'},buy=(seq,data={})=>event(seq,'souvenir',{purchaseKey:'request-'+seq,kind:'toy',day:'2026-09-13',item,amount:20,...data});
test('released catches survive merges as records and cannot be sold',async()=>{const {mergeSaves}=await import('../sport/save-merge.js'),fish={id:'fish',catchId:'catch',weight:1,time:1};const released={bag:[fish],economyEvents:[event(1,'release',{catchKey:'catch'})]};const sold={bag:[fish],economyEvents:[event(2,'sell',{catchKey:'catch',amount:100})]};for(const s of [mergeSaves(released,sold),mergeSaves(sold,released)]){assert.equal(s.bag.length,1);const w=E.account(s);assert.equal(w.money,500);assert(w.released.has('catch'));assert(!w.sold.has('catch'));assert.deepEqual(w.rejected,['2']);}});
test('cannot release sold fish or nonexistent catches',()=>{const w=E.account({bag:[{catchId:'catch'}],economyEvents:[event(1,'sell',{catchKey:'catch',amount:50}),event(2,'release',{catchKey:'catch'}),event(3,'release',{catchKey:'missing'})]});assert.equal(w.money,550);assert.equal(w.released.size,0);});
test('every paid play costs 20, same request is charged once, daily item stays fixed',()=>{const w=E.account({economyEvents:[buy(1),buy(2),buy(3,{purchaseKey:'request-1'}),buy(4,{item:{...item,id:'other'}}),buy(5,{amount:0}),buy(6,{day:'2026-09-14',item:{...item,id:'other'}})]});assert.equal(w.money,440);assert.equal(w.purchases.size,3);assert.equal(w.collection.size,2);assert.equal(w.daily.get('toy|2026-09-13').id,'yoyo');assert.deepEqual(w.rejected,['3','4','5']);});
test('cannot overspend on toys and postcards',()=>{const events=Array.from({length:26},(_,i)=>buy(i+1));const w=E.account({economyEvents:events});assert.equal(w.money,0);assert.equal(w.purchases.size,25);assert.deepEqual(w.rejected,['26']);});
test('postcard is collected only after a paid completion and duplicate completions grant no money',()=>{const paid=buy(1,{kind:'postcard',item:{...item,id:'card'}});assert.equal(E.account({economyEvents:[paid]}).collection.size,0);const w=E.account({economyEvents:[paid,event(2,'postcard-complete',{purchaseKey:'missing'}),event(3,'postcard-complete',{purchaseKey:'request-1'}),event(4,'postcard-complete',{purchaseKey:'request-1'})]});assert.equal(w.money,480);assert.equal(w.collection.size,1);assert(w.collection.has('postcard|card'));assert.deepEqual(w.rejected,['2']);});
test('daily purchases converge after cloud merge without double spending',async()=>{const {mergeSaves}=await import('../sport/save-merge.js');const a={economyEvents:[buy(1)]},b={economyEvents:[buy(2)]};const s=mergeSaves(a,b);assert.deepEqual(E.account(s),E.account(mergeSaves(b,a)));assert.equal(E.account(mergeSaves(s,s)).money,460);});
