const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
 const root=path.resolve(__dirname,'..',native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
 const c=await b.newContext({viewport:{width:1280,height:720},serviceWorkers:'block'}),missing=[],errors=[];
 await c.route('**/*',async route=>{const u=new URL(route.request().url());if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}await route.fulfill({path:f,contentType:({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});
 const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');
 await p.evaluate(()=>{chooseArea(cfg.areas[0]);showBookshop();});await p.click('#recommendBooks');assert.equal(await p.locator('.shelfBook').count(),8);
 const shot=async n=>{await p.evaluate(()=>Promise.all([...document.images].filter(x=>x.offsetWidth).map(x=>x.decode().catch(()=>{}))));await p.screenshot({path:path.resolve(__dirname,'../../..','tmp/1003-'+(native?'app-':'web-')+n+'.png')});};await shot('shelf');
 for(let i=0;i<8;i++){await p.locator('.shelfBook').nth(i).click();assert(await p.locator('.bookCopy').innerText());assert(await p.locator('.bookCover').evaluate(x=>x.complete&&x.naturalWidth>0));if(i===0)await shot('detail');await p.getByRole('button',{name:'‹ 返回書架',exact:true}).click();}
 await p.evaluate(()=>{for(let i=0;i<9;i++)transact({type:'litter',catchId:'qa-'+i,item:MarineLitter[0]});showJournal('collection',0,'objects');});assert.equal(await p.locator('.personalItem').count(),6);await shot('objects');await p.getByRole('button',{name:'下一頁',exact:true}).click();assert.equal(await p.locator('.personalItem').count(),3);await p.locator('.personalItem').first().click();await p.getByRole('button',{name:'下一件',exact:true}).click();await p.click('#objectZoom');assert(await p.locator('.objectFullscreen').isVisible());await p.getByRole('button',{name:'關閉放大',exact:true}).click();await p.getByRole('button',{name:'返回物件',exact:true}).click();assert.equal(await p.locator('.personalItem').count(),3);
 await p.evaluate(()=>{showMiniGames();playBunGame();});const frame=await(await p.locator('#islandMiniPlayer iframe').elementHandle()).contentFrame();await frame.waitForFunction(()=>typeof config!=='undefined'&&config);
 await frame.evaluate(()=>{fishingRun='qa-run';fishingLevels=[1,2,3];reportFishingReward(false);});await p.waitForFunction(()=>[...wallet().instances.keys()].some(k=>k.startsWith('certificate|')));
 const before=await p.evaluate(()=>wallet().instances.size);await frame.evaluate(()=>reportFishingReward(false));await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>wallet().instances.size),before);
 await p.evaluate(()=>{miniSession.layer.remove();miniSession=null;showJournal('collection',1,'objects');});await p.getByRole('button',{name:/平安包達人證書/}).click();await shot('certificate');assert(await p.locator('.personalObjectPreview img').evaluate(x=>x.complete&&x.naturalWidth>0));await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);assert.equal(await p.evaluate(()=>wallet().instances.size),10);
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' eight books, duplicate objects, pagination, full-screen, certificate bridge and persistence');await c.close();
 }}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
