const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const repo=path.resolve(__dirname,'..');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
const root=path.resolve(repo,native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
const c=await b.newContext({viewport:{width:1280,height:720},serviceWorkers:'block'}),missing=[],errors=[];
await c.route('**/*',async route=>{const u=new URL(route.request().url());if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}const mime={'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.webp':'image/webp','.jpg':'image/jpeg','.mp4':'video/mp4'};await route.fulfill({path:f,contentType:mime[path.extname(f)]||'application/octet-stream'});});
const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');
await p.evaluate(()=>{for(const f of cfg.fish.filter(x=>x.premium)){if(f.educationIntro.split('\n\n').length!==3||/AI|遊戲售價|紅色魚影/.test(f.educationIntro))throw Error(f.id);}chooseArea(cfg.areas[0]);showBookshop();});
for(const kind of ['toy','postcard']){
 await p.click(kind==='toy'?'#dailyToys':'#dailyPostcards');const frame=await(await p.locator('#bookshopPlayer iframe').elementHandle()).contentFrame();await frame.locator('#play').waitFor();assert((await frame.locator('.gameIntro').innerText()).includes('每日三款'));
 const ids=[];for(const value of [0,.34,.67]){await p.evaluate(v=>{window.savedRng=Math.random;Math.random=()=>v;},value);await frame.locator('#play').click();await p.waitForFunction(()=>dailySession.requests.size>0);await frame.waitForFunction(()=>!pending&&activeItem!==null);if(kind==='toy')await frame.locator('#result:not([hidden])').waitFor();else{await frame.locator('#puzzle .piece').first().waitFor();for(let i=0;i<12;i++){const j=(await frame.evaluate(()=>order.slice())).indexOf(i);if(j!==i){await frame.locator('#puzzle .piece').nth(i).click();await frame.locator('#puzzle .piece').nth(j).click();}}await frame.locator('#result:not([hidden])').waitFor();}ids.push(await frame.evaluate(()=>activeItem.id));await p.evaluate(()=>{Math.random=window.savedRng;});await frame.click('#closeResult');await frame.waitForFunction(()=>!document.getElementById('play').disabled);}
 assert.equal(new Set(ids).size,3);await p.locator('#bookshopPlayer>button').click();
}
assert.equal(await p.evaluate(()=>wallet().money),380);await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);assert.equal(await p.evaluate(()=>wallet().collection.size),6);
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' three distinct paid draws for both games, accurate intro format, money and saved collections');await c.close();
}}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
