const {test}=require('node:test'),assert=require('node:assert/strict');require('../sport/economy-core.js');const E=globalThis.CoastEconomy;
const event=(id,type,other={})=>({id:String(id),seq:id,type,...other});
test('starting wallet and bait are granted only once across merged saves',()=>{const s={economyEvents:[event(1,'buy',{bait:'master',amount:150})]};assert.equal(E.account(s).money,350);assert.equal(E.account({...s,economyEvents:E.mergeEvents(s.economyEvents,s.economyEvents)}).money,350);assert.equal(E.account(s).bait.basic,10)});
test('cannot overspend, consume empty inventory or sell same fish twice',()=>{const f={id:'a',time:1,weight:1,area:'a'},s={bag:[f],economyEvents:[event(1,'buy',{bait:'master',amount:600}),event(2,'use',{bait:'master'}),event(3,'sell',{catchKey:E.catchKey(f),amount:50}),event(4,'sell',{catchKey:E.catchKey(f),amount:50})]};const w=E.account(s);assert.equal(w.money,550);assert.equal(w.sold.size,1);assert.equal(w.rejected.length,3);assert.equal(s.bag.length,1)});
test('paid area unlock deducts once and survives merge',()=>{const a=[event(1,'unlock',{areaId:'two',amount:200})],b=[event(2,'unlock',{areaId:'two',amount:200})];const s=E.account({economyEvents:E.mergeEvents(a,b)});assert.equal(s.money,300);assert(s.areas.has('two'))});
test('concurrent offline purchases converge without negative money',()=>{const a=[event(1,'buy',{bait:'master',amount:400})],b=[{...event(1,'buy',{bait:'advanced',amount:400}),id:'other'}];const x=E.account({economyEvents:E.mergeEvents(a,b)}),y=E.account({economyEvents:E.mergeEvents(b,a)});assert.equal(x.money,100);assert.deepEqual(x,y)});
test('premium pools use unseen species exactly 60/100 when both groups exist',()=>{const all=[{id:'seen'},{id:'new'}],seen=new Set(['seen']);let count=0;for(let i=0;i<100;i++)if(E.pool(all,seen,'advanced',i/100)[0].id==='new')count++;assert.equal(count,60);assert.equal(E.pool(all,seen,'master',.99)[0].id,'new');assert.deepEqual(E.pool(all,new Set(['seen','new']),'master',0),[]);assert.equal(E.pool(all,seen,'basic',0).length,2)});
test('emergency bait only available after both money and all bait exhausted',()=>{const events=[event(1,'buy',{bait:'master',amount:500}),event(2,'use',{bait:'master'})];for(let i=0;i<10;i++)events.push(event(i+3,'use',{bait:'basic'}));events.push(event(13,'relief',{limit:10}),event(14,'relief',{limit:10}));assert.equal(E.account({economyEvents:events}).bait.basic,3);assert.equal(E.account({economyEvents:events}).money,0)});
test('cloud merger preserves ledger, catches and score separately',async()=>{const {mergeSaves}=await import('../sport/save-merge.js');const f={catchId:'fish',id:'one',weight:1,time:1};const a={bag:[f],score:200,economyEvents:[event(1,'sell',{catchKey:'fish',amount:50})]},b={bag:[f],score:200,economyEvents:[]};const s=mergeSaves(a,b);assert.equal(E.account(s).money,550);assert.equal(s.score,200);assert.equal(s.bag.length,1);assert.equal(E.account(mergeSaves(s,s)).money,550)});
