const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
 const root=path.resolve(__dirname,'..',native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
 const context=await browser.newContext({viewport:native?{width:960,height:540}:{width:1280,height:720},serviceWorkers:'block'}),errors=[],missing=[];
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='www.youtube-nocookie.com')return route.fulfill({contentType:'text/html',body:'<body style="background:#102c3b;color:white;display:grid;place-items:center;font:20px sans-serif">YouTube player</body>'});if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}await route.fulfill({path:f,contentType:({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});
 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');await p.evaluate(()=>{chooseArea(cfg.areas[0]);showBookshop();});assert.equal(await p.locator('#recommendBooks').innerText(),'店長推介');await p.click('#recommendBooks');assert.equal(await p.locator('.shelfBook').count(),8);
 const shot=async n=>{await p.evaluate(()=>Promise.all([...document.images].filter(x=>x.offsetWidth).map(x=>x.decode().catch(()=>{}))));await p.screenshot({path:path.resolve(__dirname,'../../..','tmp/manager-'+(native?'app-':'web-')+n+'.png')});};await shot('shelf');
 // A future ninth book creates a second catalogue page, not a ninth tile.
 await p.evaluate(()=>{BookshopDefaults.books.push({...BookshopDefaults.books[0],id:'qa-nine',name:'測試第九本'});showBookshelf();});await p.getByRole('button',{name:'下一頁',exact:true}).click();assert.equal(await p.locator('.shelfBook').count(),1);await p.evaluate(()=>{BookshopDefaults.books.pop();showBookshelf();});
 await p.locator('.shelfBook').nth(1).click();assert.equal(await p.locator('.bookCopy').getAttribute('data-size'),'small');await shot('detail');
 for(const [label,size] of [['中字體',26],['大字體',31],['小字體',21]]){await p.getByRole('button',{name:label,exact:true}).click();assert.equal(await p.locator('.bookCopy p').first().evaluate(x=>parseFloat(getComputedStyle(x).fontSize)),size);}
 await p.getByRole('button',{name:'大字體',exact:true}).click();await p.locator('.bookCopy').evaluate(x=>x.scrollTop=x.scrollHeight);assert(await p.locator('.bookCopy').evaluate(x=>x.scrollTop>0));await shot('large');
 const inside=await p.evaluate(()=>{const copy=document.querySelector('.bookCopy').getBoundingClientRect(),footer=document.querySelector('#modalFooter').getBoundingClientRect();return copy.bottom<footer.top-15;});assert(inside,'copy needs shelf clearance');
 await p.click('#managerMedia');for(const [i,id] of ['a7WQss1TqI0','YKiMrg6rgYQ','jBUrsbRQvGY','7z1dYHFqsTo'].entries()){assert.equal(await p.locator('#managerPlayer iframe').count(),1);assert((await p.locator('#managerPlayer iframe').getAttribute('src')).includes('/'+id+'?'));if(i===0){await p.frameLocator('#managerPlayer iframe').getByText('YouTube player',{exact:true}).waitFor();const box=await p.locator('#managerPlayer iframe').boundingBox();assert(box.width>250&&box.height>140,'inline video must be visible');await shot('media');await p.click('#managerMediaExpand');await p.waitForFunction(()=>document.fullscreenElement?.id==='managerPlayer'||!!document.querySelector('.managerVideoFallback'));await shot('fullscreen');if(await p.locator('.managerVideoFallback').count())await p.locator('.managerVideoFallback button').click();else{await p.click('#managerMediaCollapse');await p.waitForFunction(()=>!document.fullscreenElement);}}if(i<3)await p.getByRole('button',{name:'下一頁',exact:true}).click();}assert(!(await p.getByRole('button',{name:'下一頁',exact:true}).isEnabled()));
 await context.setOffline(true);await p.evaluate(()=>showManagerMedia());assert.equal(await p.locator('#managerPlayer iframe').count(),0);assert(await p.locator('.managerOffline').isVisible());await p.click('#managerBooks');assert.equal(await p.locator('.shelfBook').count(),8);await context.setOffline(false);
 await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');await p.evaluate(()=>{chooseArea(cfg.areas[0]);showBooks(0);});assert.equal(await p.locator('.bookCopy').getAttribute('data-size'),'large');await p.click('#managerBack');assert(await p.locator('#recommendBooks').isVisible());assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' independent catalogues, 8/book page, all 4 embeds, fullscreen, font persistence, text clearance and offline books');await context.close();
 }}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
