const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
 const root=path.resolve(__dirname,'..',native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
 const context=await browser.newContext({viewport:native?{width:960,height:540}:{width:1280,height:720},serviceWorkers:'block'}),errors=[],missing=[];
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='www.youtube-nocookie.com')return route.fulfill({contentType:'text/html',body:'<body style="background:#102c3b;color:white;display:grid;place-items:center;font:20px sans-serif">YouTube player</body>'});if(u.href.startsWith('https://hkrgb.github.io/island-journey-visual-novel/')){const rel=u.pathname.split('/island-journey-visual-novel/')[1]||'index.html';return route.fulfill({path:path.resolve(__dirname,'../../../tmp/island-journey-visual-novel/output',rel)});}if(u.hostname==='firestore.googleapis.com')return route.fulfill({json:{fields:{payload:{stringValue:fs.readFileSync(path.resolve(__dirname,'../../../tmp/star-story.json'),'utf8').replace(/^\uFEFF/,'')}}}});if(u.hostname==='raw.githubusercontent.com'&&u.pathname.endsWith('/game-core.js'))return route.fulfill({path:path.resolve(__dirname,'../../../tmp/novel-core-reference.js'),contentType:'text/javascript'});if(u.hostname==='raw.githubusercontent.com')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#245566"/></svg>'});if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}await route.fulfill({path:f,contentType:({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});


 const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');
 await p.evaluate(()=>{save={bag:[],medals:{},visited:{},score:7,cupWins:{},legacyImported:true,economyEvents:[]};persist();showSaveSlots();});
 assert.equal(await p.locator('.saveSlotCard').count(),3);assert.equal(await p.locator('.saveSlotCard').first().getByRole('button',{name:'讀取',exact:true}).isDisabled(),true);
 for(let i=0;i<3;i++){
  await p.evaluate(i=>{save.score=10+i;save.bag=Array.from({length:i+1},(_,n)=>({...cfg.fish[n],catchId:'slot-'+n,time:n,weight:1,area:'harbour'}));save.economyEvents=i?[{id:'certificate-'+i,seq:1,type:'certificate-import',certificate:'peaceBunMaster'}]:[];showSaveSlots();},i);
  await p.locator('.saveSlotCard').nth(i).getByRole('button',{name:'儲存',exact:true}).click();await p.getByRole('button',{name:'確認儲存',exact:true}).click();await p.getByRole('button',{name:'知道了',exact:true}).click();
 }
 await p.screenshot({path:path.resolve(__dirname,'../../../tmp/save-slots-'+(native?'app':'web')+'.png')});
 assert.deepEqual(await p.evaluate(()=>readManualSlots().map(x=>x.progress.score)),[10,11,12]);
 await p.evaluate(()=>{save.score=99;showSaveSlots();});await p.locator('.saveSlotCard').first().getByRole('button',{name:'儲存',exact:true}).click();await p.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await p.evaluate(()=>readManualSlots()[0].progress.score),10);
 await p.locator('.saveSlotCard').first().getByRole('button',{name:'讀取',exact:true}).click();await p.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await p.evaluate(()=>save.score),99);
 await p.locator('.saveSlotCard').first().getByRole('button',{name:'讀取',exact:true}).click();await p.getByRole('button',{name:'確認讀取',exact:true}).click();assert.equal(await p.evaluate(()=>save.score),10);assert.equal(await p.evaluate(()=>save.bag.length),1);assert.equal(await p.evaluate(()=>wallet().instances.size),0);assert(await p.evaluate(()=>!!save.progressTimeline.id));assert.equal(await p.locator('#home').isVisible(),false);
 await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');assert.equal(await p.evaluate(()=>save.score),10);assert.deepEqual(await p.evaluate(()=>readManualSlots().map(x=>x.progress.score)),[10,11,12]);
 await p.evaluate(()=>showSaveSlots());await p.locator('.saveSlotCard').nth(2).getByRole('button',{name:'讀取',exact:true}).click();await p.getByRole('button',{name:'確認讀取',exact:true}).click();assert.equal(await p.evaluate(()=>wallet().instances.size),1);assert.equal(await p.evaluate(()=>save.bag.length),3);
 await p.evaluate(()=>{window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith(manualSlotPrefix))throw Error('quota');return originalSet.call(this,k,v)};save.score=123;confirmManualSave(0);});await p.getByRole('button',{name:'確認覆蓋',exact:true}).click();assert.equal(await p.locator('#modalTitle').innerText(),'未能儲存');assert.equal(await p.evaluate(()=>readManualSlots()[0].progress.score),10);await p.evaluate(()=>{Storage.prototype.setItem=originalSet;});
 await p.evaluate(()=>{save.bag=[];save.economyEvents=[];showMarket();});assert.equal(await p.locator('.marketEmpty').evaluate(x=>getComputedStyle(x).color),'rgb(22, 59, 78)');await p.screenshot({path:path.resolve(__dirname,'../../../tmp/market-empty-'+(native?'app':'web')+'.png')});
 await p.evaluate(()=>{window.guestSlots=localStorage.getItem(manualSlotKey());cloud={user:{uid:'other'},changed(){}};});assert.deepEqual(await p.evaluate(()=>readManualSlots()),[null,null,null]);await p.evaluate(()=>{cloud=null;});assert.equal(await p.evaluate(()=>localStorage.getItem(manualSlotKey())===guestSlots),true);
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' three independent snapshots, cancel, full rollback, persistence, quota protection, account separation and market contrast');await context.close();
 }}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});

