const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],oldBackground=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('pro-coast.png'))oldBackground.push(r.url());});
 await page.route('https://www.gstatic.com/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());await page.goto(process.env.GAME_URL||'http://127.0.0.1:8765/mini-game/hong-kong-fishing/');await page.click('#skipFullscreen');await page.waitForFunction(()=>!cloudLoading);
 assert.equal(await page.locator('#background').evaluate(n=>getComputedStyle(n).backgroundImage),'none');
 const paths=await page.evaluate(async()=>{const result=[];for(const id of ['harbour','cheung-chau','tung-wan'])for(const period of ['morning','noon','night']){const a=cfg.areas.find(a=>a.id===id);backgroundPeriodOverride=period;await preloadPicture(areaArt(a));chooseArea(a);const url=areaArt(a);if(!$('background').style.backgroundImage.includes(url))throw Error('wrong scene');if(!$('tickerPicture').src.endsWith(id+'-noon.png'))throw Error('wrong ticker scene');result.push(url);}return result;});assert.equal(new Set(paths).size,9);for(const p of paths)assert(p.includes('locations-20260918'));
 await page.evaluate(()=>showJournal('settings'));const exit=page.locator('#personalExit'),settings=page.locator('.personalTab').nth(2);assert((await exit.boundingBox()).y>(await settings.boundingBox()).y);await page.screenshot({path:'tmp/september18-journal.png'});await exit.click();assert.equal(await page.locator('#modalTitle').textContent(),'離開遊戲？');await page.getByRole('button',{name:'取消',exact:true}).click();assert(await exit.isVisible());await exit.click();await page.getByRole('button',{name:'確定',exact:true}).click();assert.equal(await page.locator('#modalTitle').textContent(),'下次再會。');
 await page.evaluate(()=>{showIslandHub();showMiniGames();});const enter=page.locator('#enterMiniGame'),back=page.getByRole('button',{name:'返回',exact:true});assert((await enter.boundingBox()).x>(await back.boundingBox()).x);await enter.click();assert(await page.locator('#islandMiniPlayer iframe').isVisible());await page.locator('#islandMiniPlayer>button').click();assert(await enter.isVisible());
 await page.setViewportSize({width:844,height:390});await page.evaluate(()=>showJournal());await page.waitForTimeout(300);const e=await exit.boundingBox();assert(e.x>=0&&e.y>=0&&e.y+e.height<=390,JSON.stringify(e));assert.deepEqual(oldBackground,[]);assert.deepEqual(errors,[]);
 console.log('PASS: no pro-coast requests, nine scenery images/period switches, current-place noon ticker, notebook exit/cancel/save, mini-game enter/back and mobile button bounds');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
