const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const url=process.env.GAME_URL||'http://127.0.0.1:8765/mini-game/hong-kong-fishing/';
 const staticPage=await browser.newPage({javaScriptEnabled:false});await staticPage.goto(url);assert(await staticPage.locator('#modal').isHidden());await staticPage.close();
 const page=await browser.newPage({viewport:{width:1280,height:720}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://www.gstatic.com/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());await page.goto(url);await page.waitForSelector('#skipFullscreen');await page.click('#skipFullscreen');await page.waitForFunction(()=>!cloudLoading);
 const photos=await page.evaluate(()=>cfg.fish.map(f=>({id:f.id,image:f.image})));assert.equal(photos.length,150);for(const f of photos)assert(f.image.endsWith('/corrected-20260914/'+f.id+'.png'),f.id);
 const balance=await page.evaluate(()=>{
  showIslandHub();chooseArea(cfg.areas[0]);
  const sample=type=>{const species=cfg.fish.find(f=>fishSize(f).type===type);if(!species)throw Error('No size '+type);selected={species};bait={x:600,y:400};power=.5;startFight();caught.hits=4;const before=distance;held=true;update(.5);return {tension,distance:before-distance,tuning:{...fightTuning}};};
  const small=sample('small'),large=sample('large');cancelCast();
  // Fish already at the bait must still wait before testing, then nibble for 4 seconds.
  const f=school[0];selected=f;bait={x:f.x,y:f.y};biteWait=7;state='wait';stateTime=6.9;updateSeaLife(0);const early=state;stateTime=7.1;updateSeaLife(0);const nibbleState=state;stateTime=3.9;updateSeaLife(0);const beforeHook=state;stateTime=4.1;updateSeaLife(0);const hooked=state;showIslandHub();return {small,large,early,nibbleState,beforeHook,hooked};
 });assert(balance.large.tension>balance.small.tension);assert(balance.large.distance<balance.small.distance);assert.equal(balance.early,'wait');assert.equal(balance.nibbleState,'nibble');assert.equal(balance.beforeHook,'nibble');assert.equal(balance.hooked,'hook');
 await page.click('#hubBooks');await page.click('#dailyPostcards');const frame=await(await page.waitForSelector('#bookshopPlayer iframe')).contentFrame();await frame.waitForFunction(()=>typeof state!=='undefined'&&!!state);await frame.click('#play');await frame.waitForSelector('#puzzle button');
 for(let i=0;i<12;i++){const j=await frame.evaluate(i=>order.indexOf(i),i);if(i!==j){await frame.locator('#puzzle button').nth(i).click();await frame.locator('#puzzle button').nth(j).click();}}
 await frame.waitForSelector('#result:not([hidden])');await frame.click('#closeResult');await frame.click('#collectionToggle');await frame.locator('.collectionItem').first().click();
 assert(await frame.locator('#result').isVisible());assert(await frame.locator('#collectionPanel').isVisible());assert(await frame.locator('#result').evaluate(n=>{const r=n.querySelector('#resultImage').getBoundingClientRect();return n.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}));
 await frame.click('#zoomPostcard');await frame.waitForSelector('#postcardZoom');await frame.waitForFunction(()=>document.querySelector('#postcardZoom img').naturalWidth>0);assert.equal(await frame.locator('#postcardZoom img').evaluate(n=>getComputedStyle(n).objectFit),'contain');assert.equal(await frame.locator('#postcardZoom').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(0, 0, 0)');await frame.getByRole('button',{name:'關閉全屏大圖'}).click();await frame.waitForSelector('#postcardZoom',{state:'detached'});assert(await frame.locator('#result').isVisible());await frame.click('#closeResult');assert(await frame.locator('#collectionPanel').isVisible());assert.deepEqual(errors,[]);
 console.log('PASS: hidden initial modal, all 150 new image paths, longer nearby bite delay, higher large-fish tension/slower reel, collected postcard stacking, black contain fullscreen zoom and return');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
