const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const url=process.env.GAME_URL||'http://127.0.0.1:8765/mini-game/hong-kong-fishing/';
 const blank=await browser.newPage({javaScriptEnabled:false});await blank.goto(url);assert.equal(await blank.locator('#stage').evaluate(n=>getComputedStyle(n).visibility),'hidden');assert.equal(await blank.locator('body').evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(0, 0, 0)');await blank.close();
 const page=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://www.gstatic.com/**',r=>r.abort());await page.route('https://firestore.googleapis.com/**',r=>r.abort());await page.goto(url);await page.click('#skipFullscreen');await page.waitForFunction(()=>!cloudLoading);assert.equal(await page.title(),'離島旅程—從長洲出發的釣魚之旅');
 await page.evaluate(()=>showIslandHub());assert.equal(await page.locator('#returnDirectory').textContent(),'⌂ 回家');
 for(const [period,file] of [['morning','bookshop-morning.png'],['noon','bookshop-bg.jpg'],['night','bookshop-night.png']]){await page.evaluate(p=>{backgroundPeriodOverride=p;updateQuickHud();},period);assert((await page.locator('#hubBooks img').getAttribute('src')).endsWith(file));}
 await page.click('#hubBooks');await page.click('#bookshopHome');assert(await page.locator('#islandHub').isVisible());await page.click('#hubBooks');await page.click('#recommendBooks');const back=page.locator('#modalFooter .bookshopBack');assert(await back.isVisible());await page.screenshot({path:'tmp/sept16-book.png'});await back.click();
 for(const id of ['dailyToys','dailyPostcards']){await page.click('#'+id);const b=page.locator('#bookshopPlayer>.bookshopBack');assert(await b.isVisible());const box=await b.boundingBox();assert(box.x<100&&box.y>600);await b.click();assert(await page.locator('#bookshopHub').isVisible());}
 await page.evaluate(()=>{showIslandHub();showJournal();});await page.waitForFunction(()=>document.querySelector('#personalFish img')?.naturalWidth>0);assert(await page.locator('#personalFish img').isVisible());await page.screenshot({path:'tmp/sept16-journal.png'});await page.evaluate(()=>{const f={...cfg.fish[3],weight:1,catchId:'test',time:Date.now()};save.bag.unshift(f);showJournal();});assert.equal(await page.locator('#personalFish img').getAttribute('alt'),await page.evaluate(()=>save.bag[0].name));
 await page.evaluate(()=>{showIslandHub();chooseArea(cfg.areas[0]);selected=school[0];bait={x:600,y:400};startFight();});
 const a=await page.locator('#cue').boundingBox(),b=await page.locator('#fightHud').boundingBox();assert(a.y+a.height<=b.y,'cue overlaps fight HUD');await page.screenshot({path:'tmp/sept16-fight.png'});
 await page.evaluate(()=>{cancelCast();enter('ready');tickerIndex=0;updateTicker();});
 assert.equal(await page.locator('#tickerTitle').textContent(),'旅遊');assert.equal(await page.locator('#tickerPicture').evaluate(n=>n.src),await page.evaluate(()=>{const alt=$('tickerPicture').alt;return areaArt(cfg.areas.find(a=>a.name===alt),'noon');}));
 const before=await page.locator('#tickerText').evaluate(n=>new DOMMatrix(getComputedStyle(n).transform).m41);await page.waitForTimeout(1100);const after=await page.locator('#tickerText').evaluate(n=>new DOMMatrix(getComputedStyle(n).transform).m41);assert(before-after>30&&before-after<60,'steady ticker speed');assert(await page.locator('.tickerItem').count()>=2);await page.screenshot({path:'tmp/sept16-ticker.png'});
 await page.evaluate(()=>{tickerIndex=1;updateTicker();});assert.equal(await page.locator('#tickerTitle').textContent(),'魚');assert((await page.locator('#tickerPicture').getAttribute('src')).includes('corrected-20260914'));
 const weather=await page.evaluate(()=>{const previous=CoastWeather.snapshot;CoastWeather.snapshot=()=>({name:'天晴',air:{place:'長洲',value:28},airTime:new Date().toISOString(),humidity:{place:'香港天文台',value:75},uv:{place:'京士柏',value:3,desc:'中等'},sea:{place:'北角',value:27},seaTime:new Date().toISOString(),forecast:{forecastWeather:'大致天晴',forecastWind:'東風4級',forecastMintemp:{unit:'C',value:26},forecastMaxtemp:{unit:'C',value:30}}});tickerIndex=2;const item=tickerItem();CoastWeather.snapshot=previous;return item.text;});for(const text of ['相對濕度 75%','紫外線指數 3','海水溫度 27','東風4級','26–30°C'])assert(weather.includes(text),text);
 await page.clock.install();const untilNext=await page.evaluate(()=>{cfg.areas.forEach(a=>a.introText='海岸景色'.repeat(15));tickerIndex=0;updateTicker();return (document.querySelector('.tickerItem').offsetWidth-document.querySelector('.tickerWindow').clientWidth)/45*1000;});assert(untilNext>0);await page.clock.runFor(untilNext+500);assert.equal(await page.locator('#tickerTitle').textContent(),'魚');assert(await page.locator('.tickerItem').first().evaluate(n=>n.getBoundingClientRect().right>n.parentElement.parentElement.getBoundingClientRect().left),'next category starts before previous ends');await page.clock.runFor(700);assert.equal(await page.locator('#tickerTitle').evaluate(n=>n.getAnimations().length),0,'fade must settle');
 await page.setViewportSize({width:844,height:390});const mobileCue=await page.locator('#cue').evaluate(n=>{enter('fight');return n.getBoundingClientRect().bottom;});assert(mobileCue<=(await page.locator('#fightHud').boundingBox()).y);await page.screenshot({path:'tmp/sept16-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: black boot, title, home icons, period-aware preview, all bookshop return paths, notebook fish photos, separated fight HUD (desktop/mobile), continuous 45px/s ticker with timed category fades and expanded weather');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
