const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const native of [false,true]){
 const root=path.resolve(__dirname,'..',native?'android-app/app/build/generated/gameAssets/game':''),origin=native?'https://appassets.androidplatform.net/assets/game/':'https://play.rgb-workshop.com/';
 const context=await browser.newContext({viewport:native?{width:960,height:540}:{width:1280,height:720},serviceWorkers:'block'}),errors=[],missing=[];
 await context.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='www.youtube-nocookie.com')return route.fulfill({contentType:'text/html',body:'<body style="background:#102c3b;color:white;display:grid;place-items:center;font:20px sans-serif">YouTube player</body>'});if(u.href.startsWith('https://hkrgb.github.io/island-journey-visual-novel/')){const rel=u.pathname.split('/island-journey-visual-novel/')[1]||'index.html';return route.fulfill({path:path.resolve(__dirname,'../../../tmp/island-journey-visual-novel/output',rel)});}if(u.hostname==='firestore.googleapis.com')return route.fulfill({json:{fields:{payload:{stringValue:fs.readFileSync(path.resolve(__dirname,'../../../tmp/star-story.json'),'utf8').replace(/^\uFEFF/,'')}}}});if(u.hostname==='raw.githubusercontent.com'&&u.pathname.endsWith('/game-core.js'))return route.fulfill({path:path.resolve(__dirname,'../../../tmp/novel-core-reference.js'),contentType:'text/javascript'});if(u.hostname==='raw.githubusercontent.com')return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#245566"/></svg>'});if(!u.href.startsWith(origin))return route.abort();let rel=decodeURIComponent(u.pathname.slice(new URL(origin).pathname.length));if(!rel||rel.endsWith('/'))rel+='index.html';const f=path.resolve(root,rel);if(!f.startsWith(root+path.sep)||!fs.existsSync(f)){missing.push(rel);return route.fulfill({status:404,body:''});}await route.fulfill({path:f,contentType:({'.js':'text/javascript','.json':'application/json','.html':'text/html','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream'});});

 const p=await context.newPage();const tapDialogue=async fr=>{const b=await(await fr.frameElement()).boundingBox();const point=await fr.evaluate(()=>{const el=document.querySelector('#dialogue'),r=el.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2,w:innerWidth,h:innerHeight};});await p.mouse.click(b.x+point.x*b.width/point.w,b.y+point.y*b.height/point.h);};p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.waitForFunction(()=>typeof cfg!=='undefined'&&cfg&&!cloudLoading);if(!native)await p.click('#skipFullscreen');await p.evaluate(()=>{chooseArea(cfg.areas[0]);showIslandHub();});
 assert(await p.locator('#returnDirectory').evaluate(x=>x.nextElementSibling.id==='hudHearts'));await p.click('#hubTheatre');await p.locator('#theatreShelf img').first().evaluate(x=>x.decode());await p.screenshot({path:path.resolve(__dirname,'../../../tmp/theatre-'+(native?'app':'web')+'.png')});
 await p.click('#theatreLock');assert((await p.locator('#modalBody').innerText()).includes('白點泥鯭'));await p.getByRole('button',{name:'解鎖並播放',exact:true}).click();
 await p.waitForFunction(()=>theatreSession?.ready,{},{timeout:60000});assert.equal(await p.evaluate(()=>wallet().hearts),10);
 const frame=await(await p.locator('#theatrePlayer iframe').elementHandle()).contentFrame();await frame.waitForFunction(()=>document.querySelector('#reader.active'));
 assert.equal(await frame.locator('.topbar').evaluate(x=>getComputedStyle(x).display),'none');assert(await p.locator('#menu').isVisible());
 await p.evaluate(()=>dispatchEvent(new MessageEvent('message',{origin:'https://evil.invalid',data:{channel:'island-theatre',type:'complete',game:TheatreStory.game,session:theatreSession.token}})));assert.equal(await p.evaluate(()=>wallet().storyRewards.size),0);
 await frame.waitForFunction(()=>!cardBusy&&!typing);await frame.evaluate(()=>{state.i=STORY.length-1;render(false,true);});await frame.waitForFunction(()=>!typing);await tapDialogue(frame);await p.waitForFunction(()=>wallet().storyRewards.has('star-thrower'),{},{timeout:8000});assert.equal(await p.evaluate(()=>[...wallet().instances.keys()].filter(x=>x.startsWith('story|')).length),2);
 assert.equal(await p.locator('#theatrePlayer').count(),0);assert(await p.locator('#theatreShelf').isVisible());await p.locator('.theatreRewards img').first().evaluate(x=>x.decode());await p.screenshot({path:path.resolve(__dirname,'../../../tmp/theatre-reward-'+(native?'app':'web')+'.png')});await p.getByRole('button',{name:'查看物件',exact:true}).click();assert((await p.locator('#personalContent').innerText()).includes('泥鯭粥'));assert((await p.locator('#personalContent').innerText()).includes('卡片盒'));
 await p.evaluate(()=>{cfg.bookshop=cfg.bookshop||{};cfg.bookshop.toys=[{id:'fake-special',name:'泥鯭粥',image:'fake.png'}];});assert(!(await p.evaluate(()=>bookshopData().toys.some(x=>x.name==='泥鯭粥'||x.name==='卡片盒'))));assert.equal(await p.evaluate(()=>bookshopData().toys.filter(x=>['利賓納','法國有汽礦泉水','葡萄適','雙筒望遠鏡'].includes(x.name)).length),4);
 await p.evaluate(()=>showTheatre());await p.click('#theatrePlay');await p.waitForFunction(()=>theatreSession?.ready);const replay=await(await p.locator('#theatrePlayer iframe').elementHandle()).contentFrame();await replay.waitForFunction(()=>document.querySelector('#reader.active')&&!cardBusy&&!typing);await replay.evaluate(()=>{state.i=STORY.length-1;render(false,true);});await replay.waitForFunction(()=>!typing);await tapDialogue(replay);await p.waitForFunction(()=>!document.querySelector('#theatrePlayer'));assert.equal(await p.evaluate(()=>[...wallet().instances.keys()].filter(x=>x.startsWith('story|')).length),2);
 await p.evaluate(()=>showBookshop());assert.equal(await p.locator('#bookshopHome').count(),0);await p.click('#returnDirectory');assert(await p.locator('#hubTheatre').isVisible());
 await context.setOffline(true);await p.click('#hubTheatre');await p.click('#theatrePlay');assert((await p.locator('#modalBody').innerText()).includes('已解鎖資格會保留'));assert.equal(await p.locator('#theatrePlayer').count(),0);await context.setOffline(false);
 await p.reload();await p.waitForFunction(()=>cfg&&!cloudLoading);assert(await p.evaluate(()=>wallet().stories.has('star-thrower')));assert.equal(await p.evaluate(()=>wallet().storyRewards.size),1);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS '+(native?'APP':'WEB')+' theatre layout, bridge auto-start, hidden novel menu, verified completion, rewards, offline and persistence');await context.close();
 }}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
