import{initializeApp}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';import{getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut}from'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
const FIREBASE_CONFIG={projectId:'yes-card-gacha-rgb',appId:'1:496431023991:web:b62a7768104553c9958372',storageBucket:'yes-card-gacha-rgb.firebasestorage.app',apiKey:'AIzaSyB8f7LK3UR-l2UgV_6qYPgAfDNfV4YlYrM',authDomain:'yes-card-gacha-rgb.firebaseapp.com',messagingSenderId:'496431023991'},ADMIN='info@rgb-workshop.com',ROOT='https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/hongKongFishingPro',$=s=>document.querySelector(s),auth=getAuth(initializeApp(FIREBASE_CONFIG));let cfg;
function field(label,value,onchange,type='text',hint=''){const l=document.createElement('label');l.textContent=label;const i=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';i.oninput=()=>onchange(type==='number'?+i.value:i.value);l.append(i);if(hint){const s=document.createElement('span');s.className='hint';s.textContent=hint;l.append(s)}return l}
function delButton(list,item,render){const b=document.createElement('button');b.type='button';b.className='danger';b.textContent='刪除';b.onclick=()=>{list.splice(list.indexOf(item),1);render()};return b}
function card(title){const c=document.createElement('article');c.className='card';const h=document.createElement('h3');h.textContent=title;c.append(h);return c}
function renderBasic(){const b=$('#basic');b.innerHTML='';b.append(field('遊戲名稱',cfg.texts.title,v=>cfg.texts.title=v),field('準備訊息',cfg.texts.ready,v=>cfg.texts.ready=v),field('預設高級魚餌',cfg.settings.startingBait,v=>cfg.settings.startingBait=v,'number'),field('最短咬餌時間（毫秒）',cfg.settings.biteMin,v=>cfg.settings.biteMin=v,'number'),field('最長咬餌時間（毫秒）',cfg.settings.biteMax,v=>cfg.settings.biteMax=v,'number'))}
function renderFish(){const box=$('#fish');box.innerHTML='';cfg.fish.forEach(f=>{const c=card(f.name),g=document.createElement('div');g.className='card-grid';g.append(field('魚名',f.name,v=>f.name=v),field('英文名稱',f.en,v=>f.en=v),field('圖片網址',f.image,v=>f.image=v),field('最小重量 kg',f.min,v=>f.min=v,'number'),field('最大重量 kg',f.max,v=>f.max=v,'number'),field('需要命中次數',f.hits,v=>f.hits=v,'number','數字越大越難'),field('釣獲分數',f.score,v=>f.score=v,'number'));c.append(g,delButton(cfg.fish,f,renderFish));box.append(c)})}
function renderAreas(){const box=$('#areas');box.innerHTML='';cfg.areas.forEach(a=>{const c=card(a.name),g=document.createElement('div');g.className='card-grid';g.append(field('釣區名稱',a.name,v=>a.name=v),field('釣區介紹',a.description,v=>a.description=v,'textarea'),field('背景圖片網址',a.background||'assets/pro-coast.png',v=>a.background=v),field('地圖 X 位置 %',a.x,v=>a.x=v,'number'),field('地圖 Y 位置 %',a.y,v=>a.y=v,'number'),field('難度 1–4',a.difficulty,v=>a.difficulty=v,'number'));const checks=document.createElement('div');checks.className='checklist';cfg.fish.forEach(f=>{const l=document.createElement('label'),i=document.createElement('input');i.type='checkbox';i.checked=a.fish.includes(f.id);i.onchange=()=>a.fish=i.checked?[...new Set([...a.fish,f.id])]:a.fish.filter(id=>id!==f.id);l.append(i,document.createTextNode(f.name));checks.append(l)});c.append(g,checks,delButton(cfg.areas,a,renderAreas));box.append(c)})}
function renderConditions(){const box=$('#conditions');box.innerHTML='';const grid=document.createElement('div');grid.className='condition-grid';[['天氣',cfg.weather,true],['潮汐',cfg.tides,false]].forEach(([name,list,isWeather])=>{const group=document.createElement('div'),h=document.createElement('h3');h.textContent=name;group.append(h);list.forEach(o=>{const c=card(o.name),r=document.createElement('div');r.className='row';r.append(field('名稱',o.name,v=>o.name=v),field('咬餌倍率',o.bite,v=>o.bite=v,'number','大於 1 = 較快'));if(isWeather)r.append(field('張力倍率',o.tension,v=>o.tension=v,'number','大於 1 = 較難'));c.append(r);group.append(c)});grid.append(group)});box.append(grid)}
function renderTournaments(){const box=$('#tournaments');box.innerHTML='';cfg.tournaments.forEach(t=>{const c=card(t.name),g=document.createElement('div');g.className='card-grid';g.append(field('比賽名稱',t.name,v=>t.name=v),field('限時（分鐘）',t.minutes,v=>t.minutes=v,'number'),field('目標總重量 kg',t.targetKg,v=>t.targetKg=v,'number'),field('獎勵分數',t.reward,v=>t.reward=v,'number'),field('獎章 ID',t.medal,v=>t.medal=v));c.append(g,delButton(cfg.tournaments,t,renderTournaments));box.append(c)})}
function renderMedals(){const box=$('#medals');box.innerHTML='';cfg.medals.forEach(m=>{const c=card(`${m.icon} ${m.name}`),g=document.createElement('div');g.className='card-grid';g.append(field('獎章名稱',m.name,v=>m.name=v),field('圖示',m.icon,v=>m.icon=v),field('規則代碼',m.rule,v=>m.rule=v),field('目標值',m.target,v=>m.target=v));c.append(g,delButton(cfg.medals,m,renderMedals));box.append(c)})}
function render(){renderBasic();renderFish();renderAreas();renderConditions();renderTournaments();renderMedals()}
async function load(){const local=await(await fetch('config.json',{cache:'no-store'})).json(),token=await auth.currentUser.getIdToken(),r=await fetch(ROOT,{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const d=await r.json(),p=d.fields?.payload?.stringValue;cfg=p?JSON.parse(p):local}else cfg=local;render()}
async function publish(e){e.preventDefault();cfg.version=(+cfg.version||0)+1;const token=await auth.currentUser.getIdToken(),r=await fetch(ROOT,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:{payload:{stringValue:JSON.stringify(cfg)}}})});$('#status').textContent=r.ok?'已成功發佈，玩家重新開啟遊戲後生效。':'發佈失敗：'+await r.text()}
$('#loginButton').onclick=async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){$('#loginMessage').textContent='登入失敗：'+e.message}};$('#logout').onclick=()=>signOut(auth);$('#reload').onclick=load;$('#editor').onsubmit=publish;
$('#addFish').onclick=()=>{cfg.fish.push({id:`fish-${Date.now()}`,name:'新魚類',en:'',image:'../assets/yellowfin-seabream.png',min:.3,max:2,hits:4,score:100});renderFish()};$('#addArea').onclick=()=>{cfg.areas.push({id:`area-${Date.now()}`,name:'新釣區',description:'',background:'assets/pro-coast.png',x:50,y:50,difficulty:2,fish:[]});renderAreas()};$('#addTournament').onclick=()=>{cfg.tournaments.push({id:`cup-${Date.now()}`,name:'新比賽',minutes:3,targetKg:5,reward:300,medal:''});renderTournaments()};$('#addMedal').onclick=()=>{cfg.medals.push({id:`medal-${Date.now()}`,name:'新獎章',icon:'🏅',rule:'catch',target:1});renderMedals()};
onAuthStateChanged(auth,async u=>{const ok=u?.email?.toLowerCase()===ADMIN&&u.emailVerified;if(u&&!ok){await signOut(auth);$('#loginMessage').textContent='此帳戶沒有管理權限';return}$('#login').hidden=!!ok;$('#editor').hidden=!ok;if(ok){$('#userEmail').textContent=u.email;await load()}});
