const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],ROOT='https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/hongKongFishingPro',KEY='hk-fishing-pro-v1';let cfg,area=null,conditions,state='map',fish=null,distance=0,tension=18,needle=5,dir=1,raf=0,bag=[],medals={},visited={},score=0,tournament=null,tournamentKg=0,tournamentEnd=0,castAngle=0,castPower=70;const embedded=parent!==window;
function fit(){const s=Math.min(innerWidth/1280,innerHeight/720),el=$('#stage');el.style.transform=`translate(${(innerWidth-1280*s)/2}px,${(innerHeight-720*s)/2}px) scale(${s})`}addEventListener('resize',fit);fit();
function save(){const data={bag,medals,visited,score};localStorage.setItem(KEY,JSON.stringify(data));if(embedded)parent.postMessage({type:'island-stats',set:{score,fishingProBag:bag,fishingProMedals:medals},complete:false},'*')}
function loadSave(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');bag=d.bag||[];medals=d.medals||{};visited=d.visited||{};score=+d.score||0}catch{}}
async function load(){const local=await fetch('config.json',{cache:'no-store'}).then(r=>r.json());let remote;try{const r=await fetch(ROOT,{cache:'no-store'});if(r.ok){const d=await r.json();remote=JSON.parse(d.fields.payload.stringValue)}}catch{}cfg=remote?.version>=local.version?remote:local;loadSave();apply();preload();}
function apply(){document.title=cfg.texts.title;$('#title').textContent=cfg.texts.title;const w=cfg.weather[Math.floor(Date.now()/900000)%cfg.weather.length],t=cfg.tides[Math.floor(Date.now()/1800000)%cfg.tides.length];conditions={weather:w,tide:t};$('#weather').textContent=w.name;$('#tide').textContent=t.name;renderMap();renderBag();renderMedals();renderTournaments();updateCounts();createFishShadows();updateAim()}
function preload(){[...cfg.fish.map(x=>x.image),'assets/pro-coast.png'].forEach(src=>{const i=new Image;i.src=src})}
function renderMap(){const map=$('#map');map.querySelectorAll('.map-pin').forEach(x=>x.remove());cfg.areas.forEach((a,i)=>{const b=document.createElement('button');b.className='map-pin'+(area?.id===a.id?' on':'');b.style.left=a.x+'%';b.style.top=a.y+'%';b.textContent=i+1;b.title=a.name;b.onclick=()=>showArea(a,b);map.append(b)});if(!area)showArea(cfg.areas[0])}
function showArea(a){const info=$('#areaInfo');info.innerHTML=`<small>AREA ${cfg.areas.indexOf(a)+1}</small><h3>${a.name}</h3><p>${a.description}</p><p>${'★'.repeat(a.difficulty)}${'☆'.repeat(4-a.difficulty)}　難度</p><span class="weather-chip">${conditions.weather.name}</span><span class="weather-chip">${conditions.tide.name}</span><button id="goArea">前往釣點</button>`;$('#goArea').onclick=()=>selectArea(a)}
function selectArea(a){area=a;visited[a.id]=true;$('#areaName').textContent=a.name;$('#sea').style.backgroundImage=`url("${a.background||'assets/pro-coast.png'}")`;close('mapModal');state='ready';$('#action').disabled=false;$('#action').textContent='拋竿';$('#message').textContent='觀察海面的魚影，調整拋竿角度及力度。';$('#castControls').classList.remove('hidden');createFishShadows();renderMap();awardRules();save()}
function createFishShadows(){const sea=$('#fishShadows');sea.innerHTML='';for(let i=0;i<7;i++){const s=document.createElement('i');s.className='fish-shadow'+(i%2?' reverse':'')+(i===2||i===5?' near':'');s.style.top=(8+Math.random()*78)+'%';s.style.setProperty('--duration',(12+Math.random()*12)+'s');s.style.setProperty('--delay',(-Math.random()*18)+'s');s.style.setProperty('--size',(.62+Math.random()*.7).toFixed(2));s.dataset.angle=(-27+Math.random()*54).toFixed(0);s.dataset.power=(42+Math.random()*52).toFixed(0);sea.append(s)}}
function updateAim(){castAngle=+$('#castAngle').value;castPower=+$('#castPower').value;$('#angleValue').textContent=castAngle<-7?'左 '+Math.abs(castAngle)+'°':castAngle>7?'右 '+castAngle+'°':'中央';$('#powerValue').textContent=castPower+'%';const wrap=$('.rod-wrap');wrap.classList.toggle('aim-left',castAngle<-7);wrap.classList.toggle('aim-right',castAngle>7)}
function weightedFish(){const list=cfg.fish.filter(f=>area.fish.includes(f.id));return list[Math.floor(Math.random()*list.length)]||cfg.fish[0]}
function cast(){if(state!=='ready')return;state='casting';updateAim();$('#castControls').classList.add('hidden');$('#rod').className='rod cast';$('#line').className='line cast';$('#action').disabled=true;const shadows=$$('.fish-shadow'),proximity=Math.min(...shadows.map(s=>Math.hypot((castAngle-(+s.dataset.angle))/30,(castPower-(+s.dataset.power))/60)));$('#message').textContent=proximity<.42?'魚餌落在魚群附近，耐心等候魚訊…':'魚餌已落水，魚影正在慢慢靠近…';const ring=document.createElement('i');ring.className='waiting-ring';ring.style.left=(53+castAngle*.45)+'%';ring.style.top=(68-castPower*.38)+'%';$('#fishShadows').append(ring);setTimeout(()=>{$('#splash').classList.add('on')},450);setTimeout(()=>{$('#splash').classList.remove('on')},1400);const base=cfg.settings.biteMin+Math.random()*(cfg.settings.biteMax-cfg.settings.biteMin),activity=Math.max(.55,conditions.weather.bite*conditions.tide.bite),placement=proximity<.42?.7:proximity<.8?1.05:1.38;setTimeout(bite,base*placement/activity)}
function bite(){if(state!=='casting')return;$('.waiting-ring')?.remove();fish=weightedFish();distance=100;tension=16;state='fight';$('#rod').className='rod fight';$('#action').disabled=false;$('#action').textContent='收絲';$('.fight').classList.add('active');$('#message').textContent='魚上釣！在寬闊的綠色區域收絲。';tick()}
function tick(){if(state!=='fight')return;needle+=dir*(.58+fish.hits*.018)*conditions.weather.tension;if(needle>96||needle<2)dir*=-1;needle=Math.max(2,Math.min(96,needle));tension+=.018*fish.hits*conditions.weather.tension;tension=Math.max(0,Math.min(100,tension));$('#needle').style.left=needle+'%';$('#tension').style.width=tension+'%';$('#tensionText').textContent=tension>86?'危險':tension>64?'偏高':'安全';$('#distance').textContent=distance.toFixed(1);if(tension>=100)return broken();raf=requestAnimationFrame(tick)}
function reel(){if(state!=='fight')return;const good=needle>=34&&needle<=66;if(good){distance-=Math.max(10,22-fish.hits*.65);tension=Math.max(8,tension-25);$('#rod').className='rod reel';setTimeout(()=>{if(state==='fight')$('#rod').className='rod fight'},180);$('#message').textContent='漂亮收絲！魚正在接近。'}else{tension+=8;distance=Math.min(102,distance+1.5);$('#message').textContent='差一點，放鬆魚絲再試。'}if(distance<=0)land()}
function broken(){cancelAnimationFrame(raf);state='ready';fish=null;$('#rod').className='rod cast';$('.fight').classList.remove('active');$('#castControls').classList.remove('hidden');$('#action').disabled=false;$('#action').textContent='重新拋竿';$('#message').textContent='魚絲斷了。重新選擇角度與力度再試。'}
function land(){cancelAnimationFrame(raf);state='ready';const weight=+(fish.min+Math.random()*(fish.max-fish.min)).toFixed(2),caught={...fish,weight,area:area.name,time:Date.now()};bag.unshift(caught);if(tournament){tournamentKg+=weight;if(Date.now()<=tournamentEnd&&tournamentKg>=tournament.targetKg){score+=tournament.reward;medals[tournament.medal]=true;$('#message').textContent=`${tournament.name}達標，獲得 ${tournament.reward} 分及獎章！`;tournament=null}}$('#catchName').textContent=fish.name;$('#catchImage').src=fish.image;$('#catchWeight').textContent=weight+' kg';$('#catchInfo').textContent=`${fish.en} · ${area.name}`;open('catchModal');$('#rod').className='rod';$('#line').className='line';$('.fight').classList.remove('active');$('#castControls').classList.remove('hidden');$('#action').disabled=false;$('#action').textContent='再次拋竿';medals.first=true;awardRules(weight);renderBag();renderMedals();updateCounts();save()}
function awardRules(weight=0){if(weight>=10)medals.tenkg=true;if(Object.keys(visited).length>=4)medals.explorer=true}
function renderBag(){const g=$('#bagGrid');if(!g)return;g.innerHTML=bag.length?'':'<p>尚未有魚獲。</p>';bag.forEach(x=>{const a=document.createElement('article');a.tabIndex=0;a.setAttribute('role','button');a.setAttribute('aria-label',`放大查看${x.name}`);a.innerHTML=`<img src="${x.image}" alt="${x.name}"><b>${x.name}</b><span>${x.weight} kg</span><small>${x.area}</small>`;const inspect=()=>{$('#catchName').textContent=x.name;$('#catchImage').src=x.image;$('#catchWeight').textContent=x.weight+' kg';$('#catchInfo').textContent=`${x.en||''} · ${x.area}`;close('bagModal');open('catchModal')};a.onclick=inspect;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect()}};g.append(a)})}
function renderMedals(){const g=$('#medalGrid');if(!g)return;g.innerHTML='';cfg.medals.forEach(m=>{const a=document.createElement('article');a.className='medal'+(medals[m.id]?'':' locked');a.innerHTML=`<i>${m.icon}</i><b>${m.name}</b><small>${medals[m.id]?'已獲得':'尚未解鎖'}</small>`;g.append(a)})}
function renderTournaments(){const box=$('#tournamentList');if(!box)return;box.innerHTML='';cfg.tournaments.forEach(t=>{const a=document.createElement('article');a.innerHTML=`<div><b>${t.name}</b><p>${t.minutes} 分鐘內累積 ${t.targetKg} kg</p><small>獎勵 ${t.reward} 分</small></div><button>參加</button>`;a.querySelector('button').onclick=()=>{tournament=t;tournamentKg=0;tournamentEnd=Date.now()+t.minutes*60000;close('tournamentModal');$('#message').textContent=`已參加${t.name}，限時 ${t.minutes} 分鐘。`;if(!area)open('mapModal')};box.append(a)})}
function updateCounts(){$('#bagCount').textContent=bag.length;$('#medalCount').textContent=Object.values(medals).filter(Boolean).length}
function open(id){$('#'+id).classList.add('open')}function close(id){$('#'+id).classList.remove('open')}
$('#castAngle').oninput=updateAim;$('#castPower').oninput=updateAim;$('#action').onclick=()=>state==='fight'?reel():cast();$('#openMap').onclick=()=>open('mapModal');$('#openBag').onclick=()=>{renderBag();open('bagModal')};$('#openMedals').onclick=()=>{renderMedals();open('medalModal')};$('#openTournament').onclick=()=>open('tournamentModal');$('#menu').onclick=()=>open('menuModal');$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#exitGame').onclick=()=>{save();if(embedded)parent.postMessage({type:'island-stats',set:{score,fishingProBag:bag,fishingProMedals:medals},complete:true},'*')};load();
