const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const ROOT='https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/hongKongFishingPro',KEY='hk-fishing-pro-v1';
let cfg,area=null,conditions,state='map',fish=null,distance=0,tension=18,needle=5,dir=1,raf=0;
let bag=[],medals={},visited={},score=0,tournament=null,tournamentKg=0,tournamentEnd=0;
let fishSchool=[],seaRaf=0,bait=null,hookFish=null,biteAt=0,drag=null,suppressClick=false;
const embedded=parent!==window,canvas=$('#fishCanvas'),ctx=canvas.getContext('2d');

function fit(){const s=Math.min(innerWidth/1280,innerHeight/720),el=$('#stage');el.style.transform=`translate(${(innerWidth-1280*s)/2}px,${(innerHeight-720*s)/2}px) scale(${s})`}
addEventListener('resize',fit);fit();
function save(){const data={bag,medals,visited,score};localStorage.setItem(KEY,JSON.stringify(data));if(embedded)parent.postMessage({type:'island-stats',set:{score,fishingProBag:bag,fishingProMedals:medals},complete:false},'*')}
function loadSave(){try{const d=JSON.parse(localStorage.getItem(KEY)||'{}');bag=d.bag||[];medals=d.medals||{};visited=d.visited||{};score=+d.score||0}catch{}}
async function load(){const local=await fetch('config.json',{cache:'no-store'}).then(r=>r.json());let remote;try{const r=await fetch(ROOT,{cache:'no-store'});if(r.ok){const d=await r.json();remote=JSON.parse(d.fields.payload.stringValue)}}catch{}cfg=remote?.version>=local.version?remote:local;loadSave();apply();preload()}
function apply(){document.title=cfg.texts.title;$('#title').textContent=cfg.texts.title;const w=cfg.weather[Math.floor(Date.now()/900000)%cfg.weather.length],t=cfg.tides[Math.floor(Date.now()/1800000)%cfg.tides.length];conditions={weather:w,tide:t};$('#weather').textContent=w.name;$('#tide').textContent=t.name;renderMap();renderBag();renderMedals();renderTournaments();updateCounts();resetFishSchool();if(!seaRaf)animateSea()}
function preload(){[...cfg.fish.map(x=>x.image),'assets/pro-coast.png'].forEach(src=>{const i=new Image;i.src=src})}

function resetFishSchool(){fishSchool=Array.from({length:9},(_,i)=>({x:330+Math.random()*810,y:225+Math.random()*250,vx:(Math.random()<.5?-1:1)*(.28+Math.random()*.38),vy:(Math.random()-.5)*.13,size:.62+Math.random()*.72,phase:Math.random()*6.28,turn:80+Math.random()*180,index:i}));bait=null;hookFish=null}
function drawFish(f,time){const speed=Math.hypot(f.vx,f.vy),angle=Math.atan2(f.vy,f.vx),wag=Math.sin(time*.009+f.phase)*(5+speed*3);ctx.save();ctx.translate(f.x,f.y);ctx.rotate(angle);ctx.scale(f.size,f.size);ctx.globalAlpha=.22+(f.size-.6)*.12;ctx.fillStyle='#03151d';ctx.beginPath();ctx.ellipse(0,0,42,14,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-37,0);ctx.lineTo(-62,-15+wag);ctx.lineTo(-57,0);ctx.lineTo(-62,15+wag);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(-5,-9);ctx.lineTo(10,-24);ctx.lineTo(18,-8);ctx.fill();ctx.beginPath();ctx.moveTo(0,8);ctx.lineTo(14,19);ctx.lineTo(22,7);ctx.fill();ctx.globalAlpha=.34;ctx.fillStyle='#83c1c5';ctx.beginPath();ctx.arc(28,-3,1.7,0,Math.PI*2);ctx.fill();ctx.restore()}
function animateSea(time=0){ctx.clearRect(0,0,1280,720);for(const f of fishSchool){f.phase+=.015;const chasing=state==='casting'&&f===hookFish&&bait;if(chasing){const dx=bait.x-f.x,dy=bait.y-f.y,d=Math.max(1,Math.hypot(dx,dy));if(d>24){f.vx+=(dx/d*.62-f.vx)*.025;f.vy+=(dy/d*.62-f.vy)*.025}else{f.vx=Math.cos(time*.006)*.16;f.vy=Math.sin(time*.008)*.12;f.x=bait.x-22+Math.sin(time*.01)*7;f.y=bait.y+Math.cos(time*.012)*5;if(time>=biteAt)bite()}}else{f.turn--;if(f.turn<=0){f.vy+=(Math.random()-.5)*.22;f.vx+=(Math.random()-.5)*.16;f.turn=90+Math.random()*220}const neighbours=fishSchool.filter(o=>o!==f&&Math.abs(o.y-f.y)<65);if(neighbours.length)f.vy+=((neighbours.reduce((n,o)=>n+o.y,0)/neighbours.length)-f.y)*.000012;const sp=Math.hypot(f.vx,f.vy);if(sp>.72){f.vx*=.985;f.vy*=.985}if(Math.abs(f.vx)<.24)f.vx+=(f.vx>=0?1:-1)*.006}f.x+=f.vx;f.y+=f.vy;if(f.x<285){f.x=285;f.vx=Math.abs(f.vx)}if(f.x>1190){f.x=1190;f.vx=-Math.abs(f.vx)}if(f.y<205){f.y=205;f.vy=Math.abs(f.vy)}if(f.y>490){f.y=490;f.vy=-Math.abs(f.vy)}drawFish(f,time)}if(bait){ctx.save();ctx.strokeStyle='#eaffff';ctx.globalAlpha=.75;ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(bait.x,bait.y,8+Math.sin(time*.008)*3,3.5,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#f4d277';ctx.beginPath();ctx.arc(bait.x,bait.y,3,0,Math.PI*2);ctx.fill();ctx.restore()}seaRaf=requestAnimationFrame(animateSea)}

function renderMap(){const map=$('#map');map.querySelectorAll('.map-pin').forEach(x=>x.remove());cfg.areas.forEach((a,i)=>{const b=document.createElement('button');b.className='map-pin'+(area?.id===a.id?' on':'');b.style.left=a.x+'%';b.style.top=a.y+'%';b.textContent=i+1;b.title=a.name;b.onclick=()=>showArea(a);map.append(b)});if(!area)showArea(cfg.areas[0])}
function showArea(a){const info=$('#areaInfo');info.innerHTML=`<small>AREA ${cfg.areas.indexOf(a)+1}</small><h3>${a.name}</h3><p>${a.description}</p><p>${'★'.repeat(a.difficulty)}${'☆'.repeat(4-a.difficulty)}　難度</p><span class="weather-chip">${conditions.weather.name}</span><span class="weather-chip">${conditions.tide.name}</span><button id="goArea">前往釣點</button>`;$('#goArea').onclick=()=>selectArea(a)}
function selectArea(a){area=a;visited[a.id]=true;$('#areaName').textContent=a.name;$('#sea').style.backgroundImage=`url("${a.background||'assets/pro-coast.png'}")`;close('mapModal');state='ready';$('#action').disabled=false;$('#action').textContent='拋竿';$('#message').textContent='觀察魚影，按住拋竿鍵拖向想落餌的位置。';$('#castControls').classList.remove('hidden');resetFishSchool();renderMap();awardRules();save()}
function weightedFish(){const list=cfg.fish.filter(f=>area.fish.includes(f.id));return list[Math.floor(Math.random()*list.length)]||cfg.fish[0]}
function stagePoint(e){const r=$('#stage').getBoundingClientRect(),s=1280/r.width;return{x:(e.clientX-r.left)*s,y:(e.clientY-r.top)*s}}
function aimAt(p){p.x=Math.max(300,Math.min(1180,p.x));p.y=Math.max(205,Math.min(485,p.y));$('#castGuide').style.left=p.x+'px';$('#castGuide').style.top=p.y+'px';const shift=(p.x-800)*.11;$('.rod-wrap').style.transform=`translateX(${shift}px)`;return p}
function castTo(target){if(state!=='ready')return;state='casting';bait={...aimAt(target)};$('#castGuide').classList.remove('on');$('#castControls').classList.add('hidden');$('#rod').className='rod cast';$('#line').className='line cast';$('#action').classList.remove('aiming');$('#action').disabled=true;hookFish=fishSchool.reduce((best,f)=>Math.hypot(f.x-bait.x,f.y-bait.y)<Math.hypot(best.x-bait.x,best.y-bait.y)?f:best,fishSchool[0]);const separation=Math.hypot(hookFish.x-bait.x,hookFish.y-bait.y),activity=Math.max(.6,conditions.weather.bite*conditions.tide.bite),approach=2400+separation*5.5,bide=800+Math.random()*1500;biteAt=performance.now()+(approach+bide)/activity;$('#message').textContent=separation<150?'魚影發現魚餌，正在靠近試探…':'魚餌已落水，等待魚群游近…';setTimeout(()=>{$('#splash').classList.add('on')},350);setTimeout(()=>{$('#splash').classList.remove('on')},1200)}
function bite(){if(state!=='casting')return;bait=null;hookFish=null;fish=weightedFish();distance=100;tension=16;state='fight';$('#rod').className='rod fight';$('#action').disabled=false;$('#action').textContent='收絲';$('.fight').classList.add('active');$('#message').textContent='魚吞餌上釣！在寬闊的綠色區域收絲。';tick()}
function tick(){if(state!=='fight')return;needle+=dir*(.58+fish.hits*.018)*conditions.weather.tension;if(needle>96||needle<2)dir*=-1;needle=Math.max(2,Math.min(96,needle));tension+=.018*fish.hits*conditions.weather.tension;tension=Math.max(0,Math.min(100,tension));$('#needle').style.left=needle+'%';$('#tension').style.width=tension+'%';$('#tensionText').textContent=tension>86?'危險':tension>64?'偏高':'安全';$('#distance').textContent=distance.toFixed(1);if(tension>=100)return broken();raf=requestAnimationFrame(tick)}
function reel(){if(state!=='fight')return;const good=needle>=34&&needle<=66;if(good){distance-=Math.max(10,22-fish.hits*.65);tension=Math.max(8,tension-25);$('#rod').className='rod reel';setTimeout(()=>{if(state==='fight')$('#rod').className='rod fight'},180);$('#message').textContent='漂亮收絲！魚正在接近。'}else{tension+=8;distance=Math.min(102,distance+1.5);$('#message').textContent='差一點，放鬆魚絲再試。'}if(distance<=0)land()}
function readyAgain(message){cancelAnimationFrame(raf);state='ready';fish=null;bait=null;hookFish=null;$('#rod').className='rod cast';$('.fight').classList.remove('active');$('#castControls').classList.remove('hidden');$('#action').disabled=false;$('#action').textContent='重新拋竿';$('#message').textContent=message}
function broken(){readyAgain('魚絲斷了。重新觀察魚影再拋竿。')}
function land(){cancelAnimationFrame(raf);state='ready';const weight=+(fish.min+Math.random()*(fish.max-fish.min)).toFixed(2),caught={...fish,weight,area:area.name,time:Date.now()};bag.unshift(caught);if(tournament){tournamentKg+=weight;if(Date.now()<=tournamentEnd&&tournamentKg>=tournament.targetKg){score+=tournament.reward;medals[tournament.medal]=true;$('#message').textContent=`${tournament.name}達標，獲得 ${tournament.reward} 分及獎章！`;tournament=null}}$('#catchName').textContent=fish.name;$('#catchImage').src=fish.image;$('#catchWeight').textContent=weight+' kg';$('#catchInfo').textContent=`${fish.en} · ${area.name}`;open('catchModal');$('#rod').className='rod';$('#line').className='line';$('.fight').classList.remove('active');$('#castControls').classList.remove('hidden');$('#action').disabled=false;$('#action').textContent='再次拋竿';medals.first=true;awardRules(weight);renderBag();renderMedals();updateCounts();save()}
function awardRules(weight=0){if(weight>=10)medals.tenkg=true;if(Object.keys(visited).length>=4)medals.explorer=true}
function renderBag(){const g=$('#bagGrid');if(!g)return;g.innerHTML=bag.length?'':'<p>尚未有魚獲。</p>';bag.forEach(x=>{const a=document.createElement('article');a.tabIndex=0;a.setAttribute('role','button');a.innerHTML=`<img src="${x.image}" alt="${x.name}"><b>${x.name}</b><span>${x.weight} kg</span><small>${x.area}</small>`;const inspect=()=>{$('#catchName').textContent=x.name;$('#catchImage').src=x.image;$('#catchWeight').textContent=x.weight+' kg';$('#catchInfo').textContent=`${x.en||''} · ${x.area}`;close('bagModal');open('catchModal')};a.onclick=inspect;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect()}};g.append(a)})}
function renderMedals(){const g=$('#medalGrid');if(!g)return;g.innerHTML='';cfg.medals.forEach(m=>{const a=document.createElement('article');a.className='medal'+(medals[m.id]?'':' locked');a.innerHTML=`<i>${m.icon}</i><b>${m.name}</b><small>${medals[m.id]?'已獲得':'尚未解鎖'}</small>`;g.append(a)})}
function renderTournaments(){const box=$('#tournamentList');if(!box)return;box.innerHTML='';cfg.tournaments.forEach(t=>{const a=document.createElement('article');a.innerHTML=`<div><b>${t.name}</b><p>${t.minutes} 分鐘內累積 ${t.targetKg} kg</p><small>獎勵 ${t.reward} 分</small></div><button>參加</button>`;a.querySelector('button').onclick=()=>{tournament=t;tournamentKg=0;tournamentEnd=Date.now()+t.minutes*60000;close('tournamentModal');$('#message').textContent=`已參加${t.name}，限時 ${t.minutes} 分鐘。`;if(!area)open('mapModal')};box.append(a)})}
function updateCounts(){$('#bagCount').textContent=bag.length;$('#medalCount').textContent=Object.values(medals).filter(Boolean).length}
function open(id){$('#'+id).classList.add('open')}function close(id){$('#'+id).classList.remove('open')}

const action=$('#action');
action.addEventListener('pointerdown',e=>{if(state!=='ready')return;e.preventDefault();action.setPointerCapture(e.pointerId);drag={id:e.pointerId,start:stagePoint(e),target:{x:800,y:330},moved:false};action.classList.add('aiming');$('#castGuide').classList.add('on');aimAt(drag.target)});
action.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const p=stagePoint(e);drag.target=aimAt(p);drag.moved=drag.moved||Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>18});
action.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;e.preventDefault();const target=drag.moved?drag.target:{x:800,y:330};drag=null;suppressClick=true;castTo(target);setTimeout(()=>suppressClick=false,80)});
action.onclick=()=>{if(suppressClick)return;if(state==='fight')reel()};
$('#openMap').onclick=()=>open('mapModal');$('#openBag').onclick=()=>{renderBag();open('bagModal')};$('#openMedals').onclick=()=>{renderMedals();open('medalModal')};$('#openTournament').onclick=()=>open('tournamentModal');$('#menu').onclick=()=>open('menuModal');$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#exitGame').onclick=()=>{save();if(embedded)parent.postMessage({type:'island-stats',set:{score,fishingProBag:bag,fishingProMedals:medals},complete:true},'*')};load();
