'use strict';
const $ = id => document.getElementById(id);
const stage = $('stage'), water = $('water'), ctx = water.getContext('2d'), rig = $('tackle').getContext('2d');
const ROOT = 'https://firestore.googleapis.com/v1/projects/yes-card-gacha-rgb/databases/(default)/documents/miniGames/hongKongFishingPro';
const KEY = 'coastline-sport-save-v1', BASE = new URL('../pro/', document.baseURI);
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const rand = (a,b) => a+Math.random()*(b-a);
const esc = v => String(v??'').replace(/[&<>"']/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset = path => {path=globalThis.FishImagePath?.(path)||path;if(!path)return '';try{const u=new URL(path,BASE);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
let cfg, area, weather, tide, fishList=[], school=[], selected=null, caught=null;
let state='loading', time=0, stateTime=0, last=0, heading=0, power=.55, held=false, pressedAt=0;
let bait=null, target={x:640,y:435}, distance=0, tension=0, stamina=1, surge=false, over=0, nibble=0;
let tournament=null, dialogOpen=true, dialogReturn=null, toast='', toastUntil=0, lastFocus=null;
let save={bag:[],medals:{},visited:{},score:0,cupWins:{}};
const embedded=parent!==window;
let cloud=null,cloudMessage='訪客模式 · 只儲存在此瀏覽器',cloudLoading=!embedded;
let hostReady=false,hostOrigin='*',hostScore=0,sessionReward=0,legacyProgress={},hostCertificates={},pendingPrize=null;
const art=name=>new URL('assets/'+name+'.png',document.baseURI).href;
function areaArt(a){const p=a.backgrounds?.[scenePeriod()]||a.background||a.backgroundUrl;return p&&!p.endsWith('assets/pro-coast.png')?asset(p):art(['cheung-chau','lantau','ninepins','po-toi'].includes(a.id)?a.id:'cheung-chau')}
function setScene(){if(!area)return;stage.dataset.dayPeriod=tournament?'noon':scenePeriod();$('background').style.backgroundImage='url("'+(tournament?(tournament.background?asset(tournament.background):art('competition')):areaArt(area))+'")';stage.classList.toggle('competition',!!tournament);$('location').textContent=tournament?'海港競技場 · '+area.name:area.name}
function report(done=false){if(!embedded||!hostReady)return;parent.postMessage({type:'island-stats',set:{score:hostScore+sessionReward,fishingBag:save.bag,fishingProgress:{...legacyProgress,coastline:{medals:save.medals,visited:save.visited,score:save.score,cupWins:save.cupWins,lastArea:save.lastArea,cupRewards:save.cupRewards||{},economyEvents:save.economyEvents||[]}},certificates:hostCertificates},complete:done},hostOrigin)}
addEventListener('message',e=>{const d=e.data;if(!embedded||e.source!==parent||d?.type!=='island-stats')return;if(d.request==='dump'){report();return}if(hostReady)return;hostOrigin=e.origin==='null'?'*':e.origin;hostScore=Number.isFinite(+d.score)?+d.score:0;legacyProgress=d.fishingProgress&&typeof d.fishingProgress==='object'?d.fishingProgress:{};hostCertificates=d.certificates||{};const p=legacyProgress.coastline||{};save={bag:Array.isArray(d.fishingBag)?d.fishingBag:[],medals:p.medals||{},visited:p.visited||{},score:+p.score||0,cupWins:p.cupWins||{},cupRewards:p.cupRewards||{},lastArea:p.lastArea,economyEvents:p.economyEvents||[]};hostReady=true;updateLog();updateAccount()});
const rings=[];
const rodImage=new Image();rodImage.src='../assets/rod-pro.png';
function fit(){const w=visualViewport?.width||document.documentElement.clientWidth,h=visualViewport?.height||document.documentElement.clientHeight,s=Math.min(w/1280,h/720);stage.style.transform=`translate(${(w-1280*s)/2}px,${(h-720*s)/2}px) scale(${s})`}
addEventListener('resize',fit);visualViewport?.addEventListener('resize',fit);fit();
function isFullscreen(){return !!(document.fullscreenElement||document.webkitFullscreenElement)}
function refreshFullscreen(){const active=isFullscreen(),button=$('fullscreenJourney');if(button){button.textContent=active?'退出全屏幕':'全屏幕';button.setAttribute('aria-pressed',String(active))}if(!active){try{screen.orientation?.unlock?.()}catch{}}fit();requestAnimationFrame(fit);setTimeout(fit,250)}
document.addEventListener('fullscreenchange',refreshFullscreen);document.addEventListener('webkitfullscreenchange',refreshFullscreen);addEventListener('orientationchange',refreshFullscreen);
async function toggleFullscreen(){
 const note=$('fullscreenNote');if(note){note.hidden=true;note.textContent=''}
 try{
  if(isFullscreen()){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document)}
  else{const root=document.documentElement,request=root.requestFullscreen||root.webkitRequestFullscreen;if(!request)throw Error('unsupported');await request.call(root);try{await screen.orientation?.lock?.('landscape')}catch{}}
 }catch{if(note){note.hidden=false;note.textContent='此瀏覽器或嵌入視窗未能開啟全屏幕。仍會保持 16:9；手機可轉橫向瀏覽。'}}
 refreshFullscreen();
}
function loadSave(){if(embedded)return;try{const d=JSON.parse(localStorage.getItem(KEY)||'null');if(d&&Array.isArray(d.bag))save={...save,...d};else{const old=JSON.parse(localStorage.getItem('hk-fishing-pro-v1')||'{}');if(Array.isArray(old.bag))save.bag=old.bag.map(f=>({...f,image:asset(f.image)}));save.medals=old.medals||{};save.visited=old.visited||{}}if(!save.legacyImported){const legacy=JSON.parse(localStorage.getItem('hong-kong-fishing-bag-v4')||'[]');const keys=new Set(save.bag.map(f=>f.id+':'+f.time));for(const f of legacy)if(!keys.has(f.id+':'+f.time)){save.bag.push({...f,image:new URL(f.image,new URL('../',document.baseURI)).href});keys.add(f.id+':'+f.time)}save.legacyImported=true;localStorage.setItem(KEY,JSON.stringify(save))}}catch{}}
function persist(){if(embedded){report();updateLog();return}if(cloud?.user){cloud.changed();updateLog();return}try{localStorage.setItem(KEY,JSON.stringify(save))}catch{toast='儲存空間不足，今次進度未能保存。';toastUntil=time+10}updateLog()}
function updateLog(){updateWallet();$('total').textContent=save.bag.length;$('best').textContent=save.bag.length?save.bag.reduce((n,f)=>Math.max(n,+f.weight||0),0).toFixed(2):'—'}
function valid(c){return c&&Array.isArray(c.fish)&&c.fish.some(f=>f.id)&&Array.isArray(c.areas)&&c.areas.length}
async function init(){try{let base=await fetch('../pro/config.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('config');return r.json()});try{const r=await fetch(ROOT,{signal:AbortSignal.timeout(4000)});if(r.ok){const d=await r.json(),remote=JSON.parse(d.fields?.payload?.stringValue||'null');if(valid(remote))base=remote}}catch{}if(!valid(base))throw Error('設定未齊備');cfg=RegionGuide.normalize(base);cfg.weather=cfg.weather?.length?cfg.weather:[{name:'天晴',bite:1,tension:1}];cfg.tides=cfg.tides?.length?cfg.tides:[{name:'漲潮',bite:1}];cfg.tournaments=cfg.tournaments||[];cfg.medals=cfg.medals||[];loadSave();updateLog();state='ready';setupHome();showHome();setupEconomy();if(!embedded)setupCloud();requestAnimationFrame(frame)}catch(e){modal('未能載入釣區','請檢查網絡後重新開啟。',()=>{location.reload()},'重新載入',true)}}
function cue(phase,hint,sub){$('phase').textContent=phase;$('hint').textContent=hint;$('subhint').textContent=sub}
function enter(s){state=s;stateTime=0;stage.dataset.state=s;held=false;$('action').classList.remove('held');$('powerHud').hidden=s!=='charge';$('fightHud').hidden=s!=='fight';$('action').disabled=['loading','flight','landed'].includes(s);const labels={ready:['拋竿','按住蓄力，放手拋出'],charge:['放手','拋出魚餌'],flight:['拋投中',''],wait:['收回','重新選擇落餌位置'],nibble:['等一等','浮標完全下沉時揚竿'],hook:['揚竿！','現在按一下'],fight:['收魚絲','按住收魚絲 · 放手卸力'],landed:['魚獲','']};const l=labels[s]||labels.ready;$('actionTitle').textContent=l[0];$('actionHint').textContent=l[1];if(s==='ready')cue('01 / 尋找魚蹤','點海面選方向，再按住拋竿蓄力。','輕按拋竿亦可用中等力度。空白鍵可代替拋竿／收魚絲。');if(s==='wait')cue('03 / 等待魚訊','魚餌入水了，留意浮標。','魚群會自行游近；浮標輕點是試餌，先別揚竿。');if(s==='nibble')cue('04 / 試餌','魚正在啄餌，等浮標完全下沉。','輕微晃動不是中魚訊號。');if(s==='hook')cue('05 / 揚竿','浮標沉了——現在揚竿！','按一下右下方按鈕。');if(s==='fight')cue('06 / 搏魚','穩住魚竿，按住收魚絲。','魚衝刺時放手卸力，張力回落後再收。')}
function chooseArea(a){if(!economyReady())return;if(!areaOwned(a)){requestArea(a);return;}$('home').hidden=true;cancelCast();area=a;save.lastArea=a.id;fishList=cfg.fish.filter(f=>a.fish?.includes(f.id));weather=cfg.weather[Math.floor(time/120)%cfg.weather.length];tide=cfg.tides[Math.floor(time/180)%cfg.tides.length];$('location').textContent=a.name;refreshConditions();setScene();save.visited[a.id]=true;school=Array.from({length:8},(_,i)=>({x:rand(330,1000),y:rand(370,530),angle:rand(-Math.PI,Math.PI),desired:0,turn:rand(1,4),size:rand(.5,1),speed:rand(15,24),phase:rand(0,6),species:RegionGuide.weighted(fishList,area)}));school.forEach(f=>f.desired=f.angle);closeDialog();enter('ready');award();persist()}
function cancelCast(){bait=null;selected=null;held=false;rings.length=0}
function ready(message){cancelCast();enter('ready');if(message)cue('再試一次',message,'魚獲與比賽紀錄已保留。')}
function cast(){if(!useCastBait()){enter('ready');return;}power=clamp(power,.18,1);target={x:640+Math.sin(heading)*(200+power*250),y:545-power*175};bait={x:1000,y:625};enter('flight');cue('02 / 拋投','魚絲正沿拋物線送出。',`預計落點 ${(12+power*34).toFixed(0)} 米`)}
function startFight(){caught={...selected.species};distance=12+power*34;tension=22;stamina=1;over=0;enter('fight');ring(bait.x,bait.y);}
function land(){if(selected)selected.species=RegionGuide.weighted(fishList,area);const f=caught,firstDiscovery=!hasCaught(f);const min=Math.max(.01,+f.min||.3),max=Math.max(min,+f.max||2);const weight=+rand(min,max).toFixed(2),entry={firstDiscovery,catchId:crypto.randomUUID(),id:f.id,name:f.name,en:f.en||'',scientificName:f.scientificName||'',family:f.family||'',image:asset(f.image),weight,area:area.name,time:Date.now()};save.bag.unshift(entry);if(tournament&&tournament.remaining>0){tournament.kg+=weight;if(tournament.kg>=tournament.targetKg){const already=save.cupWins[tournament.id];save.cupWins[tournament.id]=true;if(tournament.medal)save.medals[tournament.medal]=true;if(!already){const reward=Math.max(0,+tournament.reward||0);save.score+=reward;save.cupRewards={...(save.cupRewards||{}),[tournament.id]:reward};sessionReward+=reward}pendingPrize={...tournament,already};toast=`${tournament.name}達標！${already?'完成重賽':`獲得 ${tournament.reward} 分`}`;toastUntil=time+12;tournament=null;setScene()}}award();persist();cancelCast();enter('landed');showFish(entry,true)}
function award(){for(const m of cfg.medals){const n=+m.target;if(m.rule==='catch'&&save.bag.length>=n||m.rule==='areas'&&Object.keys(save.visited).length>=n||m.rule==='weight'&&save.bag.some(f=>f.weight>=n)||m.rule==='tournament'&&save.cupWins[m.target])save.medals[m.id]=true}}
function ring(x,y){rings.push({x,y,age:0})}
function update(dt){time+=dt;stateTime+=dt;if(tournament){tournament.remaining-=dt;if(tournament.remaining<=0){toast='比賽時間到，下次再挑戰。魚獲已保留。';toastUntil=time+10;tournament=null;setScene()}}$('cupStatus').textContent=tournament?`${tournament.name}\n${Math.ceil(tournament.remaining)} 秒 · ${tournament.kg.toFixed(2)} / ${tournament.targetKg} kg`:toastUntil>time?toast:`自由垂釣`;
if(state==='charge'){power=.18+Math.min(stateTime/1.6,1)*.82;$('power').style.width=power*100+'%'}
if(state==='flight'){const t=clamp(stateTime/1,0,1);bait.x=1000+(target.x-1000)*t;bait.y=625+(target.y-625)*t-Math.sin(t*Math.PI)*190;if(t===1){ring(target.x,target.y);selected=attractedFish();enter('wait')}}
updateSeaLife(dt);
if(state==='hook'&&stateTime>4.5)ready('魚把餌吐掉了。下次看到浮標下沉便揚竿。');
if(state==='fight'){surge=Math.sin(stateTime*.85)> .55;const difficulty=clamp(+caught.hits||4,2,12);stamina=Math.max(0,stamina-dt*.027);tension+=dt*(held?(surge?25:10)+difficulty*.35:-24);tension=clamp(tension,3,100);if(held&&tension<91)distance-=dt*(surge?.5:3.7)*(1.25-stamina*.25);else if(!held&&surge)distance+=dt*.65;distance=clamp(distance,0,70);over=tension>96?over+dt:0;if(over>1.6){ready('魚絲斷了：紅色張力時要放手卸力。');return}if(distance<=0){land();return}$('strain').style.width=tension+'%';$('strain').style.background=tension>78?'#ef9177':'#9bd2bb';$('strainLabel').textContent=tension>78?'張力偏高 · 放手！':surge?'魚正在衝刺 · 卸力':'魚已放慢 · 可以收魚絲';$('fishDistance').textContent=distance.toFixed(1)+' m';bait.x=target.x+Math.sin(stateTime*.8)*45;bait.y=target.y+(1-distance/50)*50;}
for(const r of rings)r.age+=dt;while(rings[0]?.age>2)rings.shift();}
function drawWater(){ctx.clearRect(0,0,1280,720);if(!area)return;CoastMotion.atmosphere(ctx,liveConditions);ctx.save();ctx.beginPath();ctx.rect(290,332,850,260);ctx.clip();for(const f of school)drawNaturalFish(f);ctx.restore();CoastMotion.waves(ctx);for(const r of rings){ctx.strokeStyle=`rgba(226,241,232,${(1-r.age/2)*.5})`;ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(r.x,r.y,8+r.age*35,3+r.age*9,0,0,Math.PI*2);ctx.stroke()}}
function floatDetail(){if(!['wait','nibble','hook'].includes(state))return;rig.save();rig.translate(1133,240);rig.beginPath();rig.arc(0,0,65,0,Math.PI*2);rig.fillStyle='#123749ed';rig.fill();rig.strokeStyle=state==='hook'?'#e7c382':'#85a2ab77';rig.lineWidth=2;rig.stroke();rig.save();rig.clip();rig.strokeStyle='#a5d7d46b';for(let i=0;i<5;i++){rig.beginPath();rig.ellipse(Math.sin(time+i)*5,12+i*12,60,4,0,0,Math.PI*2);rig.stroke()}const y=state==='hook'?55:state==='nibble'?Math.sin(stateTime*9)*9:Math.sin(time*2)*2;rig.translate(Math.sin(time)*3,y);rig.fillStyle='#f1e3b5';rig.fillRect(-4,-42,8,59);rig.fillStyle='#e5795f';rig.fillRect(-4,-42,8,18);rig.beginPath();rig.ellipse(0,11,9,14,0,0,Math.PI*2);rig.fillStyle='#edd6a0';rig.fill();rig.restore();rig.fillStyle='#e7d6ad';rig.font='12px sans-serif';rig.textAlign='center';rig.fillText(state==='hook'?'浮標下沉 · 揚竿！':'浮標特寫',0,88);rig.restore()}
function drawRig(){rig.clearRect(0,0,1280,720);if(!area)return;const swing=state==='charge'?-power*.2:state==='flight'?Math.sin(clamp(stateTime,0,1)*Math.PI)*.45:state==='fight'?.06+Math.sin(time*(surge?8:2))*.018:0;const angle=heading*.12+swing,ox=1010,oy=810,dx=-235,dy=-647;const tip={x:ox+dx*Math.cos(angle)-dy*Math.sin(angle),y:oy+dx*Math.sin(angle)+dy*Math.cos(angle)};
if(bait){rig.beginPath();rig.moveTo(tip.x,tip.y);rig.quadraticCurveTo((tip.x+bait.x)/2,Math.max(tip.y,bait.y)+ (state==='fight'?0:35),bait.x,bait.y);rig.strokeStyle='rgba(235,246,237,.65)';rig.lineWidth=.8;rig.stroke()}
rig.save();rig.translate(ox,oy);rig.rotate(angle);if(!CoastMotion.draw(rig)&&rodImage.complete&&rodImage.naturalWidth)rig.drawImage(rodImage,-370,-690,480,720);rig.restore();
if(bait){const bob=state==='nibble'?Math.sin(stateTime*10)*4:Math.sin(time*2)*1.5;const sunk=state==='hook';if(!sunk){rig.save();rig.translate(bait.x,bait.y+bob);rig.fillStyle='#e2dbb6';rig.fillRect(-2,-14,4,16);rig.fillStyle='#e05c44';rig.fillRect(-2,-23,4,10);rig.fillStyle='#eee8cd';rig.beginPath();rig.ellipse(0,-3,4,6,0,0,Math.PI*2);rig.fill();rig.restore()}else{rig.strokeStyle='#f2dd96';rig.beginPath();rig.ellipse(bait.x,bait.y,14,4,0,0,Math.PI*2);rig.stroke()}}
if(['ready','charge'].includes(state)){const x=640+Math.sin(heading)*(200+power*250),y=545-power*175;rig.setLineDash([4,5]);rig.strokeStyle='#e5d3a9aa';rig.lineWidth=1;rig.beginPath();rig.ellipse(x,y,23,7,0,0,Math.PI*2);rig.stroke();rig.setLineDash([]);rig.fillStyle='#ede4ce';rig.font='12px sans-serif';rig.fillText((12+power*34).toFixed(0)+' m',x-15,y-17)}}
function frame(now){const dt=Math.min(.04,Math.max(0,(now-last)/1000));last=now;fishingFeedback(dt);CoastMotion.update(dt,state==='fight'&&held,dialogOpen||document.hidden||!area);if(!dialogOpen&&!document.hidden&&area)update(dt);drawWater();drawRig();floatDetail();requestAnimationFrame(frame)}
function modal(title,body,ok,label='確定',compact=false){document.querySelector('.dialog').classList.remove('journalDialog');$('modalKicker').textContent='COASTLINE';held=false;if(state==='charge')enter('ready');dialogOpen=true;lastFocus=document.activeElement;$('modal').hidden=false;$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalFooter').replaceChildren();document.querySelector('.dialog').classList.toggle('compact',compact);if(ok)foot(label,ok,true);$('closeModal').disabled=!area;$('closeModal').focus()}
function foot(label,fn,primary=false){const b=document.createElement('button');b.textContent=label;b.className=primary?'primary':'';b.onclick=fn;$('modalFooter').append(b);return b}
function closeDialog(){if(!area||!$('home').hidden)return;dialogOpen=false;$('modal').hidden=true;held=false;if(state==='landed')enter('ready');(lastFocus?.isConnected?lastFocus:$('action')).focus()}
function showLegacyAreas(first=false){$('home').hidden=true;modal(first?'從一片海岸開始。':'選擇下一處釣點','<div class="areaGrid"></div>');const g=$('modalBody').firstChild;for(const [i,a] of cfg.areas.entries()){const b=document.createElement('button');b.className='areaCard';b.style.backgroundImage=`url("${areaArt(a)}")`;b.innerHTML=`<small>COAST ${String(i+1).padStart(2,'0')}</small><b>${esc(a.name)}</b><p>${esc(a.description)}<br>${areaOwned(a)?'已解鎖 · 免費進入':'解鎖 $'+areaPrice(a)}<br>${(a.fish||[]).length} 種魚</p>`;b.disabled=!cfg.fish.some(f=>a.fish?.includes(f.id));b.onclick=()=>requestArea(a);g.append(b)}foot('玩法說明',showHelp);foot('商街 · $'+wallet().money,openHarbour);foot('主選單',showHome);}
function showHelp(){modal('聽見海的節奏。','<div class="intro"><em>01</em> 點海面選方向，按住拋竿蓄力，放手送出魚餌。<br><em>02</em> 浮標輕點是試餌；完全下沉時，按一下「揚竿」。<br><em>03</em> 按住「收魚絲」拉近魚，張力變橙時放手卸力。<br><em>04</em> 魚獲會存入手帳，可以按圖片放大欣賞。</div>',()=>area?closeDialog():showAreas(),'知道了');}
function fishPresentation(f){return fishMarkup(f)+'<div class="fishIdentity"><h2>'+esc(f.name)+'</h2><small>'+esc(f.en||'')+'</small></div><div class="fishCapture">'+(Number.isFinite(+f.weight)?'<p><strong>'+Number(f.weight).toFixed(2)+'</strong> kg</p>':'')+(f.area?'<p>'+esc(f.area)+(f.time?'<br>'+new Date(f.time).toLocaleDateString('zh-HK'):'')+'</p>':'')+'</div>';}
function showFish(f,newCatch=false){modal('魚獲紀錄','<div class="detail fishShowcase">'+(newCatch&&f.firstDiscovery?'<img class="newDiscovery" src="assets/new-discovery.webp" alt="NEW · 首次發現">':'')+fishPresentation(f)+'</div>',()=>newCatch?(pendingPrize?showPrize():closeDialog()):showBag(),pendingPrize&&newCatch?'領取獎盃':'繼續');}
function showBag(page=0){const pages=Math.max(1,Math.ceil(save.bag.length/8));page=clamp(page,0,pages-1);modal('魚獲手帳',save.bag.length?'<div class="grid"></div>':'<p class="intro">第一尾魚的故事，等你寫下。</p>');if(save.bag.length){const g=$('modalBody').firstChild;for(const f of save.bag.slice(page*8,page*8+8)){const b=document.createElement('button');b.className='fishCard';b.innerHTML=fishMarkup(f)+`<b>${esc(f.name)}</b><small>${Number(f.weight).toFixed(2)} kg · ${esc(f.area)}</small>`;b.onclick=()=>showFish(f);g.append(b)}}foot('上一頁',()=>showBag(page-1)).disabled=page===0;const s=document.createElement('span');s.textContent=`${page+1} / ${pages}`;$('modalFooter').append(s);foot('下一頁',()=>showBag(page+1)).disabled=page===pages-1;}
function showCups(page=0){return;const list=cfg.tournaments.slice(page*3,page*3+3);modal('海港競技場 · 海釣賽事','<div class="cupBanner">CHAMPIONSHIP / 在燈火海港挑戰重量紀錄</div>');for(const t of list){const row=document.createElement('div');row.className='row';row.innerHTML=`<img class="cupThumb" src="${art('trophy')}" alt="海釣獎盃"><div><b>${esc(t.name)}</b><p>${t.minutes} 分鐘 · 累積 ${t.targetKg} kg · 首次達標 ${t.reward} 分</p></div>`;const b=document.createElement('button');b.textContent=tournament?'比賽進行中':save.cupWins[t.id]?'再次挑戰':'報名參加';b.disabled=!!tournament||!area;b.onclick=()=>{tournament={...t,remaining:Math.max(1,+t.minutes||3)*60,kg:0};cancelCast();enter('ready');setScene();closeDialog()};row.append(b);$('modalBody').append(row)}foot('上一頁',()=>showCups(page-1)).disabled=page===0;foot('下一頁',()=>showCups(page+1)).disabled=(page+1)*3>=cfg.tournaments.length;}
function showMedals(page=0){modal('榮譽獎章','<div class="grid"></div>');for(const m of cfg.medals.slice(page*8,page*8+8)){const el=document.createElement('div');el.className='fishCard '+(save.medals[m.id]?'':'locked');el.innerHTML=`${m.rule==='tournament'?`<img src="${art('trophy')}" alt="獎盃">`:`<span style="font-size:48px;padding:22px">${esc(m.icon)}</span>`}<b>${esc(m.name)}</b><small>${save.medals[m.id]?'已獲得':'尚未獲得'}</small>`;if(m.rule==='tournament'&&save.medals[m.id]){el.setAttribute('role','button');el.tabIndex=0;el.onclick=()=>showPrize({name:m.name,already:true},true);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')el.click()}}$('modalBody').firstChild.append(el)}foot('上一頁',()=>showMedals(page-1)).disabled=page===0;foot('下一頁',()=>showMedals(page+1)).disabled=(page+1)*8>=cfg.medals.length;}
function showPrize(prize=pendingPrize,fromGallery=false){if(!prize)return;pendingPrize=null;modal(fromGallery?'榮譽珍藏':'挑戰成功 · 獎盃授予',`<div class="detail prize"><img src="${art('trophy')}" alt="金色海釣冠軍獎盃"><div><small>COASTLINE CHAMPIONSHIP</small><h2>${esc(prize.name)}</h2><p>${prize.already?'榮譽已收藏在你的獎章頁。':`首次達標 · +${Math.max(0,+prize.reward||0)} 分`}</p><p>每一次耐心等待，都成就這一刻。</p></div></div>`,()=>fromGallery?showMedals():closeDialog(),'繼續');}
function menu(){showJournal()}
function press(){if(dialogOpen)return;if(state==='ready'){if(!canBaitCast())return;pressedAt=time;enter('charge');held=true}else if(state==='hook')startFight();else if(state==='fight')held=true;else if(state==='wait')ready('已收回魚餌，可以重新拋投。');$('action').classList.toggle('held',held)}
function release(cancel=false){if(state==='charge'){if(cancel)enter('ready');else{if(time-pressedAt<.18)power=.55;cast()}}held=false;$('action').classList.remove('held')}
$('action').addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();$('action').setPointerCapture(e.pointerId);press()});$('action').addEventListener('pointerup',()=>release());$('action').addEventListener('pointercancel',()=>release(true));$('action').addEventListener('lostpointercapture',()=>{if(held)release(true)});
water.addEventListener('pointerdown',e=>{if(dialogOpen||state!=='ready')return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)*1280/r.width;heading=clamp((x-640)/460,-1.1,1.1)});
addEventListener('keydown',e=>{if(e.code==='Space'&&!dialogOpen){e.preventDefault();if(!e.repeat)press()}if(e.code==='Escape'){if(dialogOpen)closeDialog();else menu()}if(dialogOpen&&e.key==='Tab'){const all=[...$('modal').querySelectorAll('button:not(:disabled)')];const first=all[0],end=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus()}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus()}}});addEventListener('keyup',e=>{if(e.code==='Space')release()});addEventListener('blur',()=>release(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)release(true)});
$('closeModal').onclick=closeDialog;$('menu').onclick=menu;$('mapButton').onclick=()=>showAreas();$('bagButton').onclick=()=>showBag();$('medalsButton').onclick=()=>showMedals();
function guestSave(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||{bag:[],medals:{},visited:{},score:0,cupWins:{}}}catch{return {bag:[],medals:{},visited:{},score:0,cupWins:{}}}}
function setupHome(){
 const h=document.createElement('section');h.id='home';h.setAttribute('aria-label','遊戲主選單');
 h.innerHTML='<div class="homeShade"></div><div class="homeCenter"><small>COASTLINE / HONG KONG</small><h1 id="homeTitle"></h1><p id="homeSubtitle"></p><div class="homeActions"><button id="newJourney">開始遊戲</button><button id="loadJourney">讀取進度</button><button id="fullscreenJourney" aria-pressed="false">全屏幕</button><button id="exitJourney">離開遊戲</button></div><p id="fullscreenNote" role="status" hidden></p><div id="accountActions"><button id="googleLogin">使用 Google 登入</button><button id="cloudSync" hidden>立即同步</button><button id="importGuest" hidden>匯入訪客進度</button><button id="googleLogout" hidden>登出</button></div><p id="cloudState" role="status"></p><button id="exportSave">下載存檔備份</button></div>';
 stage.append(h);
 $('newJourney').onclick=()=>showAreas(true);$('loadJourney').onclick=loadJourney;$('exitJourney').onclick=exitJourney;$('fullscreenJourney').onclick=toggleFullscreen;refreshFullscreen();
 $('googleLogin').onclick=async()=>{cloudLoading=true;updateAccount();await cloud?.login();cloudLoading=false;updateAccount()};$('cloudSync').onclick=()=>cloud?.sync();$('googleLogout').onclick=()=>{modalAccount('登出 Google？','尚未同步的進度仍保存在此裝置的帳戶備份，登出後返回訪客存檔。',()=>cloud.logout())};
 $('importGuest').onclick=()=>modalAccount('匯入訪客進度？','把這個瀏覽器的訪客魚獲合併到目前 Google 帳戶。相同紀錄不會重複，原本訪客存檔會保留。',()=>cloud.importGuest());
 $('exportSave').onclick=()=>{const b=new Blob([JSON.stringify(save,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='coastline-save-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
}
function modalAccount(title,text,action){$('home').hidden=true;modal(title,'<p class="intro">'+esc(text)+'</p>',async()=>{await action();showHome()},'確定',true);foot('取消',showHome)}
function showHome(){cancelCast();tournament=null;pendingPrize=null;held=false;dialogOpen=true;$('modal').hidden=true;const p=cfg.presentation||{};$('home').hidden=false;$('home').style.backgroundImage='url("'+(p.coverImage?asset(p.coverImage):art('opening'))+'")';$('homeTitle').textContent=p.title||'潮境';$('homeSubtitle').textContent=p.subtitle||'海釣紀行 · 每一次等待，都是新的故事';updateAccount();$('newJourney').focus()}
function updateAccount(){if(!$('home'))return;$('cloudState').textContent=embedded?'故事模式 · 由主程式保存進度':cloudMessage;$('accountActions').hidden=embedded;$('googleLogin').hidden=!!cloud?.user;$('googleLogin').disabled=cloudLoading||!cloud;$('cloudSync').hidden=!cloud?.user;$('googleLogout').hidden=!cloud?.user;$('importGuest').hidden=!cloud?.user;$('newJourney').disabled=cloudLoading||(embedded&&!hostReady);$('loadJourney').disabled=cloudLoading||(embedded&&!hostReady)}
async function setupCloud(){
 try{const module=await import('./cloud.js?v=20260909-economy');cloud=module.createCloud({
 read:()=>JSON.parse(JSON.stringify(save)),readGuest:guestSave,
 replace:d=>{save=d;updateLog()},
 guest:()=>{save=guestSave();updateLog()},
 status:(message,user)=>{cloudLoading=false;cloudMessage=(user?(user.displayName||user.email||'Google 玩家')+' · ':'')+message;updateAccount()}
 });updateAccount()}
 catch{cloudLoading=false;cloudMessage='Google 服務未能載入，仍可使用訪客模式。';updateAccount()}
}
function loadJourney(){const a=cfg.areas.find(a=>a.id===save.lastArea);if(a){requestArea(a);return}$('home').hidden=true;modal('讀取進度','<p class="intro">'+(save.bag.length?'已讀取 '+save.bag.length+' 尾魚獲，請選擇釣區繼續。':'未有垂釣紀錄。你可以開始旅程，或返回主選單登入 Google 讀取雲端存檔。')+'</p>',()=>showAreas(true),'選擇釣區',true);foot('返回主選單',showHome)}
function showAreaIntro(a,page=0){if(!areaOwned(a)){requestArea(a);return;}$('home').hidden=true;const picture=a.introImage?asset(a.introImage):areaArt(a),copy=a.introText||a.description||'放慢步伐，細看這片海的魚訊。',pages=Math.ceil(copy.length/160);page=clamp(page,0,Math.max(0,pages-1));modal(a.introTitle||a.name,'<div class="placeIntro"><img src="'+esc(picture)+'" alt="'+esc(a.name)+'介紹圖片"><div><small>DESTINATION / HONG KONG</small><h2>'+esc(a.name)+'</h2><p>'+esc(copy.slice(page*160,page*160+160))+'</p></div></div>',()=>enterAreaLoaded(a),'進入遊戲');foot('返回釣區',()=>showRegionAreas(a.category));if(pages>1){foot('上一頁',()=>showAreaIntro(a,page-1)).disabled=page===0;foot('下一頁',()=>showAreaIntro(a,page+1)).disabled=page===pages-1}}
function exitJourney(){$('home').hidden=true;modal('離開遊戲？','<p class="intro">'+(embedded?'進度會交回主程式。':'請確認雲端顯示「已同步」，或下載備份後才關閉瀏覽器。')+'</p>',()=>{persist();if(embedded){report(true)}else{modal('下次再會。','<p class="intro">本次遊戲已暫停；請留意以下存檔狀態再關閉分頁。<br>'+esc(cloudMessage)+'</p>',showHome,'返回主選單',true)}},'確定',true);foot('取消',showHome)}

function fishMarkup(f){const current=cfg.fish.find(item=>item.id===f.id),url=current?.image||f.image;return url?'<img loading="lazy" decoding="async" src="'+esc(asset(url))+'" alt="'+esc(f.name)+'">':'<div class="missingFish"><span>魚類資料</span><b>'+esc(f.name)+'</b><small>專屬圖片待補</small></div>'}
function showCatalog(page=0,query=''){
 const q=query.trim().toLowerCase(),list=cfg.fish.filter(f=>(!q||hasCaught(f))&&[f.name,f.en,f.scientificName,f.family].some(v=>String(v||'').toLowerCase().includes(q))),pages=Math.max(1,Math.ceil(list.length/8));
 page=clamp(page,0,pages-1);modal('香港海魚資料庫','<div class="catalogSearch"><input id="catalogQuery" placeholder="搜尋已釣獲的魚名／學名" aria-label="搜尋魚庫"><button id="findFish">搜尋</button><span>'+list.length+' 種結果</span></div><div class="grid catalogGrid"></div>');
 const regionFish=[...new Map(cfg.fish.filter(f=>!area||area.fish?.includes(f.id)).map(f=>[f.id,f])).values()],collected=regionFish.filter(hasCaught).length;
 $('modalKicker').textContent=(area?area.name:'全部釣區')+' · 已收集 '+collected+' / '+regionFish.length+' 種 · 尚欠 '+(regionFish.length-collected)+' 種';
 $('catalogQuery').value=query;$('findFish').onclick=()=>showCatalog(0,$('catalogQuery').value);$('catalogQuery').onkeydown=e=>{if(e.key==='Enter')$('findFish').click()};
 const g=$('modalBody').querySelector('.grid');
 for(const f of list.slice(page*8,page*8+8)){const b=document.createElement('button');b.className='fishCard';if(!hasCaught(f)){b.classList.add('undiscovered');b.disabled=true;b.innerHTML=unknownFish()+'<b>未解鎖</b><small>釣獲後顯示資料</small>';g.append(b);continue;}b.innerHTML=fishMarkup(f)+'<b>'+esc(f.name)+'</b><small>'+esc(f.scientificName||f.en)+'</small>';b.onclick=()=>{const caught=[...save.bag].reverse().find(x=>x.id===f.id);modal('魚類資料','<div class="detail fishShowcase">'+fishPresentation({...caught,...f,weight:caught?.weight,area:caught?.area,time:caught?.time})+'</div>',()=>showCatalog(page,query),'返回魚庫')};g.append(b)}
 foot('上一頁',()=>showCatalog(page-1,query)).disabled=page===0;foot((page+1)+' / '+pages,()=>{}).disabled=true;foot('下一頁',()=>showCatalog(page+1,query)).disabled=page===pages-1;
}

const atlas=document.createElement('button');atlas.id='catalogButton';atlas.textContent='魚類資料庫';atlas.onclick=()=>showCatalog();document.querySelector('nav').append(atlas);
init();
