/* Premium fish release data. Applied to local AND older remote configurations; no save writes. */
(function(root){
const fish=[
  {
    "id": "cromileptes-altivelis",
    "name": "老鼠斑",
    "en": "Humpback grouper",
    "scientificName": "Cromileptes altivelis",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/cromileptes-altivelis.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 480,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 480,
    "source": "https://www.fishbase.se/summary/6457",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "老鼠斑（Cromileptes altivelis）是石斑魚類，頭部較小，背部明顯隆起，淡色身體及魚鰭散布黑色圓點。\n\n分布於東印度洋至西太平洋，棲息在潟湖及外礁，也可見於帶泥沙的礁區。\n\n生態趣味：以小魚和甲殼類為食，生長較慢；高背、小頭和圓點，是辨認牠的好線索。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-lanceolatus",
    "name": "龍躉",
    "en": "Giant grouper",
    "scientificName": "Epinephelus lanceolatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-lanceolatus.png",
    "min": 0.5,
    "max": 12,
    "hits": 8,
    "score": 420,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 420,
    "source": "https://www.fishbase.se/summary/6468",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "龍躉（Epinephelus lanceolatus）是體型龐大的石斑魚，頭大、嘴闊，成魚多呈深褐色，魚鰭可見細小黑點。\n\n廣布印度－太平洋，可在岩礁洞穴、沉船及河口活動，亦見於較淺水域。\n\n辨認：幼魚有鮮明的黃黑斑塊，長大後體色會變暗；牠會捕食魚類及甲殼類，不能只按顏色認種。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-fuscoguttatus",
    "name": "老虎斑",
    "en": "Brown-marbled grouper",
    "scientificName": "Epinephelus fuscoguttatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-fuscoguttatus.png",
    "min": 0.5,
    "max": 5,
    "hits": 8,
    "score": 360,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 360,
    "source": "https://fishesofaustralia.net.au/Home/species/4670",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "老虎斑（Epinephelus fuscoguttatus）是大型石斑魚，黃褐色身體上有密集小褐點和不規則深色斑塊，尾柄上方有黑色鞍斑。\n\n分布於印度－太平洋熱帶礁區，常在珊瑚豐富的潟湖、通道和外礁斜坡活動；幼魚也會利用海草床。\n\n生態趣味：繁殖時會聚集產卵。斑塊及尾柄黑斑可作辨認線索，但要與外形相似的杉斑仔細比較。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-polyphekadion",
    "name": "杉斑",
    "en": "Camouflage grouper",
    "scientificName": "Epinephelus polyphekadion",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-polyphekadion.png",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 380,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 380,
    "source": "https://fishesofaustralia.net.au/Home/species/4511",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "杉斑（Epinephelus polyphekadion）是石斑魚類，淺褐色身體布滿小深色點，較大的暗斑形成斜帶，尾柄上方有明顯黑斑。\n\n分布於印度－太平洋，棲息在潟湖和外礁的珊瑚區，島嶼及環礁一帶較常見。\n\n辨認：外觀容易與老虎斑混淆；杉斑的斜帶通常較清楚，尾柄黑斑也較大，不能單靠市場俗名判斷。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-bruneus",
    "name": "泥斑",
    "en": "Longtooth grouper",
    "scientificName": "Epinephelus bruneus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-bruneus.png",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 320,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 320,
    "source": "https://www.fao.org/4/t0540e/t0540e19.pdf",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "泥斑（Epinephelus bruneus）是身形較修長的石斑魚，成魚多呈暗灰褐色，身上有淡色細斑，尾鰭後緣圓弧。\n\n見於西北太平洋沿岸的岩礁及泥底，成魚可在較深水域活動，幼魚則較靠近淺水。香港有歷史紀錄。\n\n辨認：幼魚有較清楚的深色斜帶，成魚的帶紋會變淡；觀察年齡造成的花紋變化，有助理解同種魚的不同模樣。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-awoara",
    "name": "黃斑",
    "en": "Yellow grouper",
    "scientificName": "Epinephelus awoara",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-awoara.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 220,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 220,
    "source": "https://fishbase.se/summary/Epinephelus-awoara",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "黃斑（Epinephelus awoara）是石斑魚類，背側灰褐，腹側常帶金黃色，身上有暗帶，尾鰭及背鰭軟條部的邊緣常呈黃色。\n\n分布於西北太平洋至南海，棲息在岩石區及沙泥底；幼魚可出現在潮池。香港人工魚礁名錄有紀錄。\n\n辨認：留意鰭緣黃色與身上的暗帶，不宜只看整體體色；同一尾魚在不同環境下，顏色深淺也可有差別。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-bleekeri",
    "name": "長尾芝麻斑",
    "en": "Bleeker’s grouper",
    "scientificName": "Epinephelus bleekeri",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-bleekeri.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 240,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 240,
    "source": "https://www.fao.org/4/t0540e/t0540e19.pdf",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "長尾芝麻斑（Epinephelus bleekeri）是石斑魚類，身體較修長，頭部及身上有許多橙褐色小點，尾鰭下部較深色。\n\n分布於印度－西太平洋，主要在近海淺灘及岩石底活動，並非典型的茂密珊瑚礁魚。香港有歷史紀錄。\n\n辨認：尾鰭上下部的色差是重要線索；「芝麻斑」可指不同魚種，要把斑點、尾形及鰭色一起比較。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-quoyanus",
    "name": "玳瑁石斑",
    "en": "Longfin grouper",
    "scientificName": "Epinephelus quoyanus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-quoyanus.png",
    "min": 0.5,
    "max": 2,
    "hits": 6,
    "score": 200,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 200,
    "source": "https://www.fishbase.se/summary/Epinephelus-quoyans.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "玳瑁石斑（Epinephelus quoyanus）是石斑魚類，淡色底上密布深褐色圓斑至六角斑，胸鰭寬厚，尾鰭較圓。\n\n分布於西太平洋，偏好近岸帶泥沙的礁區，通常獨自行動。香港人工魚礁名錄有紀錄。\n\n生態趣味：會捕食蝦、蟹、小魚和蠕蟲。寬厚的胸鰭與牠經常停棲在海底的習性有關。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "plectropomus-areolatus",
    "name": "西星斑",
    "en": "Squaretail coralgrouper",
    "scientificName": "Plectropomus areolatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-areolatus.png",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 460,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 460,
    "source": "https://fishesofaustralia.net.au/home/species/4516",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "西星斑（Plectropomus areolatus）是星斑類石斑，體色可淡灰至灰褐，身上有帶深色邊的藍點，尾鰭後緣較平直。\n\n棲息在熱帶礁區，澳洲北部的外海礁群亦有分布，與其他星斑一樣是礁區的掠食者。\n\n生態趣味：成魚以魚類為食。辨認時可留意藍點、較方的尾形，以及尾鰭後緣的細白邊。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "plectropomus-laevis",
    "name": "皇帝星斑",
    "en": "Blacksaddled coralgrouper",
    "scientificName": "Plectropomus laevis",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-laevis.png",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 520,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 520,
    "source": "https://fishesofaustralia.net.au/home/species/4517",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "皇帝星斑（Plectropomus laevis）是星斑類石斑，體色有不同型態；灰色型的頭部較暗，背上有深色鞍斑，身上散布細小藍點。\n\n棲息在熱帶潟湖及向海的礁區，可見於澳洲北部及珊瑚海的礁群。\n\n生態趣味：幼魚能模仿有毒的黑背尖鼻魨外觀。幼魚和成魚的模樣不同，不能只以一張成魚照片辨種。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "plectropomus-maculatus",
    "name": "泰星斑",
    "en": "Spotted coralgrouper",
    "scientificName": "Plectropomus maculatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-maculatus.png",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 400,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 400,
    "source": "https://fishesofaustralia.net.au/home/species/4519",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "泰星斑（Plectropomus maculatus）是星斑類石斑，體色可紅、灰或褐，身上有藍點，頭部及前半身部分斑點呈橫向短線。\n\n主要分布於熱帶西太平洋的沿岸礁區，常在較混濁或帶泥沙的近岸水域活動。\n\n辨認：頰部拉長的藍色短紋，是與其他星斑比較的線索；幼魚的縱帶和深色斑點則與成魚不同。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "variola-louti",
    "name": "燕尾星斑",
    "en": "Yellow-edged lyretail",
    "scientificName": "Variola louti",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/variola-louti.png",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 440,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 440,
    "source": "https://reeflife.org/species/variola-louti/",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "燕尾星斑（Variola louti）是石斑魚類，身上密布細小藍點，尾鰭呈新月形，上下兩端延長，尾緣有寬黃邊。\n\n分布於熱帶印度－太平洋礁區，體色可由深紅變到淺灰，野外常單獨出現。\n\n辨認：新月形尾巴配上黃色尾緣很有特色；近似的白邊燕尾星斑，尾緣則呈白色。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "cephalopholis-sonnerati",
    "name": "紅瓜子斑",
    "en": "Tomato hind",
    "scientificName": "Cephalopholis sonnerati",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/cephalopholis-sonnerati.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 390,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 390,
    "source": "https://fishesofaustralia.net.au/home/species/4658",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "紅瓜子斑（Cephalopholis sonnerati）是石斑魚類，體色多呈紅至紅褐色，身上可有細點，頭部背面輪廓隆起。\n\n分布於印度－太平洋，棲息在沿岸岩礁、較深的潟湖礁及外礁斜坡。\n\n生態趣味：多獨自行動，捕食小魚和甲殼類；英文俗名 Tomato hind，也呼應了牠常見的紅色外觀。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "cheilinus-undulatus",
    "name": "蘇眉",
    "en": "Humphead wrasse",
    "scientificName": "Cheilinus undulatus",
    "family": "Labridae",
    "image": "../sport/assets/premium-fish/cheilinus-undulatus.png",
    "min": 0.5,
    "max": 8,
    "hits": 8,
    "score": 650,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 650,
    "source": "https://australian.museum/learn/animals/fishes/humphead-maori-wrasse-cheilinus-undulatus/",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "蘇眉（Cheilinus undulatus）屬隆頭魚科，成魚額頭隆起、嘴唇厚，體色多帶綠色，頭身有波浪紋，眼後有兩條深色線。\n\n分布於印度－西太平洋及中太平洋的熱帶礁區，大型個體常在外礁陡坡活動。\n\n生態趣味：是體型最大的隆頭魚，會吃軟體動物、甲殼類、海膽及魚類；額頭隆起的外形比顏色更容易辨認。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "eleutheronema-tetradactylum",
    "name": "馬友",
    "en": "Fourfinger threadfin",
    "scientificName": "Eleutheronema tetradactylum",
    "family": "Polynemidae",
    "image": "../sport/assets/premium-fish/eleutheronema-tetradactylum.png",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 240,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 240,
    "source": "https://www.fishbase.se/summary/Eleutheronema-tetradactylum.html",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "馬友（Eleutheronema tetradactylum）屬馬鮁科，身體銀亮修長，胸鰭下方有四條游離的絲狀鰭條，活魚的胸鰭常帶黃色。\n\n主要見於印度洋至澳洲北部一帶的近岸淺泥底及河口。東亞另有外形相近的四指馬鮁屬魚，俗名不能單獨用來辨種。\n\n生態趣味：成魚會捕食蝦和魚。胸鰭下方的「四條絲」是醒目特徵，但要連同鰭色和其他細節判斷。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "pampus-argenteus",
    "name": "白鯧",
    "en": "Silver pomfret",
    "scientificName": "Pampus argenteus",
    "family": "Stromateidae",
    "image": "../sport/assets/premium-fish/pampus-argenteus.png",
    "min": 0.5,
    "max": 2,
    "hits": 6,
    "score": 200,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 200,
    "source": "https://fishdb.sinica.edu.tw/mobi/species.php?gen=Pampus&spe=argenteus",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "白鯧（Pampus argenteus）屬鯧科，身體高而側扁，銀白色，嘴小；背鰭和臀鰭前端延長，成魚沒有腹鰭。\n\n棲息在沿岸沙泥底水域，可成群在中層活動，分布於印度－西太平洋一帶。\n\n生態趣味：會吃水母和其他浮游動物。白鯧類外形相近，銀白色和扁身只是初步線索，還要比較鰭形等特徵。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "pampus-chinensis",
    "name": "斗鯧",
    "en": "Chinese silver pomfret",
    "scientificName": "Pampus chinensis",
    "family": "Stromateidae",
    "image": "../assets/fish/review-20261008/pampus-chinensis.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 280,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 280,
    "source": "https://www.fishbase.se/summary/Pampus-chinensis.html",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "斗鯧（Pampus chinensis）屬鯧科，身體高而側扁，呈銀灰色，頭小、嘴小，細鱗容易脫落，側線沿著背部輪廓延伸。\n\n分布於印度－西太平洋的沿岸水域，常在泥底上方活動，有時進入河口，可單獨或成小群出現。\n\n生態趣味：食物包括櫛水母、水母、樽海鞘及其他浮游動物，也會吃小型底棲動物。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "larimichthys-crocea",
    "name": "大黃花",
    "en": "Large yellow croaker",
    "scientificName": "Larimichthys crocea",
    "family": "Sciaenidae",
    "image": "../sport/assets/premium-fish/larimichthys-crocea.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 230,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 230,
    "source": "https://www.fishbase.se/summary/Larimichthys-crocea.html",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "大黃花（Larimichthys crocea）屬石首魚科，身體修長，鮮活時常帶金黃色，背鰭後方的軟條部延伸較長。\n\n分布於西北太平洋，主要在沿岸及河口的泥底或泥沙底水域活動。\n\n生態趣味：以甲殼類及魚類為食，也是重要的養殖魚種；市場供應和野生族群的狀況不能混為一談。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "trachinotus-blochii",
    "name": "黃立鯧",
    "en": "Snubnose pompano",
    "scientificName": "Trachinotus blochii",
    "family": "Carangidae",
    "image": "../sport/assets/premium-fish/trachinotus-blochii.png",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 180,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 180,
    "source": "https://fishesofaustralia.net.au/home/species/2993",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "黃立鯧（Trachinotus blochii）屬鰺科，身體高而側扁，吻部圓鈍，銀灰色身體可帶金黃色，尾鰭深叉。\n\n廣布熱帶印度－太平洋，成魚常在沿岸礁緣活動，幼魚可成群出現在河口附近的沙泥底淺水區。\n\n生態趣味：會吃硬殼軟體動物及其他無脊椎動物。名字雖然帶「鯧」，卻與白鯧、斗鯧分屬不同科。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-malabaricus",
    "name": "花鬼斑",
    "en": "Malabar grouper",
    "scientificName": "Epinephelus malabaricus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-malabaricus.png",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 300,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 300,
    "source": "https://www.fishbase.se/summary/Epinephelus-malabaricus.html",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "ai-photorealistic-real-reference",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "花鬼斑（Epinephelus malabaricus）是石斑魚類，身體灰至黃褐色，頭身布有細小黑點和不規則暗斑，尾鰭呈圓弧。\n\n廣布印度－太平洋，可在岩礁、珊瑚礁、河口、紅樹林及沙泥底活動，幼魚較常利用近岸與河口。\n\n生態趣味：多獨自行動，主要吃魚和甲殼類，也會吃頭足類。與青斑等近似種比較時，要仔細看斑點和花紋。",
    "educationRevision": "20260929-verified",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  }
];
function apply(config){
 config.fish=config.fish||[];
 for(const entry of fish){const prior=config.fish.find(f=>f.id===entry.id);if(prior)Object.assign(prior,structuredClone(entry));else config.fish.push(structuredClone(entry));}
 for(const area of config.areas||[]){const ids=fish.filter(f=>f.gameAreas.includes(area.id)).map(f=>f.id);area.fish=[...new Set([...(area.fish||[]),...ids])];}
 return config;
}
root.PremiumFish={fish,apply};
})(globalThis);
