/* Premium fish release data. Applied to local AND older remote configurations; no save writes. */
(function(root){
const fish=[
  {
    "id": "cromileptes-altivelis",
    "name": "老鼠斑",
    "en": "Humpback grouper",
    "scientificName": "Cromileptes altivelis",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/cromileptes-altivelis.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 480,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 480,
    "source": "https://www.afcd.gov.hk/english/fisheries/ar/faunas_of_ar/fish_ar.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "頭部小、背部高起，淡色身體及魚鰭散布深色圓點。香港人工魚礁歷史名錄有紀錄。\n\n香港本地歷史紀錄；不代表現今各釣區調查。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-lanceolatus",
    "name": "龍躉",
    "en": "Giant grouper",
    "scientificName": "Epinephelus lanceolatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-lanceolatus.svg",
    "min": 0.5,
    "max": 12,
    "hits": 8,
    "score": 420,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 420,
    "source": "https://www.afcd.gov.hk/english/conservation/Con_hkbsap/bsap_links_to_resources/files/Final_Report_Sustainable_Use_EF_ES_FG.pdf",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "頭大嘴闊、身形粗壯，是大型石斑。香港活珊瑚魚市場有交易紀錄。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-fuscoguttatus",
    "name": "老虎斑",
    "en": "Brown-marbled grouper",
    "scientificName": "Epinephelus fuscoguttatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-fuscoguttatus.svg",
    "min": 0.5,
    "max": 5,
    "hits": 8,
    "score": 360,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 360,
    "source": "https://www.afcd.gov.hk/english/conservation/Con_hkbsap/bsap_links_to_resources/files/Final_Report_Sustainable_Use_EF_ES_FG.pdf",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "黃褐底色上帶不規則深色斑塊和細點，形成大理石般花紋。屬香港市場交易的石斑。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-polyphekadion",
    "name": "杉斑",
    "en": "Camouflage grouper",
    "scientificName": "Epinephelus polyphekadion",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-polyphekadion.svg",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 380,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 380,
    "source": "https://www.afcd.gov.hk/english/conservation/Con_hkbsap/bsap_links_to_resources/files/Final_Report_Sustainable_Use_EF_ES_FG.pdf",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "體表密布褐色斑點與雲狀花紋，是珊瑚礁底棲石斑。香港市場有進口交易。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-bruneus",
    "name": "泥斑",
    "en": "Longtooth grouper",
    "scientificName": "Epinephelus bruneus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-bruneus.svg",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 320,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 320,
    "source": "https://www.afcd.gov.hk/english/fisheries/ar/faunas_of_ar/fish_ar.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "深褐色粗壯身體，幼魚的斜帶較清楚。香港人工魚礁歷史名錄有紀錄。\n\n香港本地歷史紀錄；不代表現今各釣區調查。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "epinephelus-awoara",
    "name": "黃斑",
    "en": "Yellow grouper",
    "scientificName": "Epinephelus awoara",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-awoara.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 220,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 220,
    "source": "https://www.afcd.gov.hk/english/fisheries/ar/faunas_of_ar/fish_ar.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "頭身有細斑，身體後部與鰭常帶黃色。與魚庫原有的青斑是不同物種。\n\n香港本地歷史紀錄；不代表現今各釣區調查。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-bleekeri",
    "name": "長尾芝麻斑",
    "en": "Bleeker’s grouper",
    "scientificName": "Epinephelus bleekeri",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-bleekeri.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 240,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 240,
    "source": "https://www.afcd.gov.hk/english/fisheries/ar/faunas_of_ar/fish_ar.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "身體有橙褐色細點，尾鰭上、下部色澤不同。不要與原有的齊尾芝麻斑混淆。\n\n香港本地歷史紀錄；不代表現今各釣區調查。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-quoyanus",
    "name": "玳瑁石斑",
    "en": "Longfin grouper",
    "scientificName": "Epinephelus quoyanus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-quoyanus.svg",
    "min": 0.5,
    "max": 2,
    "hits": 6,
    "score": 200,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 200,
    "source": "https://www.afcd.gov.hk/english/fisheries/ar/faunas_of_ar/fish_ar.html",
    "recordBasis": "香港本地歷史紀錄；不代表現今各釣區調查",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "身體及頭部有緊密的褐色多角形斑，像玳瑁紋。香港礁區有紀錄。\n\n香港本地歷史紀錄；不代表現今各釣區調查。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "plectropomus-areolatus",
    "name": "西星斑",
    "en": "Squaretail coralgrouper",
    "scientificName": "Plectropomus areolatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-areolatus.svg",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 460,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 460,
    "source": "https://seafood-guide.wwf.org.hk/zh/node/1131",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "身體散布藍色圓點，尾緣較平直。屬香港市場的星斑類，並非每個本地釣點都有。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "plectropomus-laevis",
    "name": "皇帝星斑",
    "en": "Blacksaddled coralgrouper",
    "scientificName": "Plectropomus laevis",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-laevis.svg",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 520,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 520,
    "source": "https://seafood-guide.wwf.org.hk/zh/node/1131",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "常見色型有淡色身體、深色鞍狀斑及黃色鰭；亦有較深色型。香港市場有交易。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "plectropomus-maculatus",
    "name": "泰星斑",
    "en": "Spotted coralgrouper",
    "scientificName": "Plectropomus maculatus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/plectropomus-maculatus.svg",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 400,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 400,
    "source": "https://seafood-guide.wwf.org.hk/zh/node/1131",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "紅褐色身上散布藍點，體形較修長。與原有東星斑屬同一屬的不同物種。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "variola-louti",
    "name": "燕尾星斑",
    "en": "Yellow-edged lyretail",
    "scientificName": "Variola louti",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/variola-louti.svg",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 440,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 440,
    "source": "https://seafood-guide.wwf.org.hk/zh/node/1131",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "尾鰭呈明顯新月形，邊緣帶黃；身體帶細斑。主要按香港海鮮市場魚種加入。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "cephalopholis-sonnerati",
    "name": "紅瓜子斑",
    "en": "Tomato hind",
    "scientificName": "Cephalopholis sonnerati",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/cephalopholis-sonnerati.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 390,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 390,
    "source": "https://kmweb.moa.gov.tw/subject/subject.php?id=63247&print=Y",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "身體紅至橙紅，常有網狀斑紋，尾鰭圓。屬具經濟價值的珊瑚礁石斑類。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "cheilinus-undulatus",
    "name": "蘇眉",
    "en": "Humphead wrasse",
    "scientificName": "Cheilinus undulatus",
    "family": "Labridae",
    "image": "../sport/assets/premium-fish/cheilinus-undulatus.svg",
    "min": 0.5,
    "max": 8,
    "hits": 8,
    "score": 650,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 650,
    "source": "https://www.afcd.gov.hk/english/conservation/Con_hkbsap/bsap_links_to_resources/files/Final_Report_Sustainable_Use_EF_ES_FG.pdf",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "成魚前額隆起、嘴唇厚，身體有細密紋路。香港市場有交易紀錄，野生資源需珍惜。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  },
  {
    "id": "eleutheronema-tetradactylum",
    "name": "馬友",
    "en": "Fourfinger threadfin",
    "scientificName": "Eleutheronema tetradactylum",
    "family": "Polynemidae",
    "image": "../sport/assets/premium-fish/eleutheronema-tetradactylum.svg",
    "min": 0.5,
    "max": 4,
    "hits": 6,
    "score": 240,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 240,
    "source": "https://www.fmo.org.hk/price?fid=5&id=3&page=3&path=12_43&per-page=10",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "身體銀亮，胸鰭下有四條游離絲狀鰭條，常在沿岸沙泥底活動。香港魚市場有報價。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "pampus-argenteus",
    "name": "白鯧",
    "en": "Silver pomfret",
    "scientificName": "Pampus argenteus",
    "family": "Stromateidae",
    "image": "../sport/assets/premium-fish/pampus-argenteus.svg",
    "min": 0.5,
    "max": 2,
    "hits": 6,
    "score": 200,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 200,
    "source": "https://www.fmo.org.hk/price?fid=5&id=3&page=3&path=12_43&per-page=10",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "身體銀白、側扁而高，口小、尾分叉。香港食用魚市場的重要鯧魚。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "pampus-chinensis",
    "name": "斗鯧",
    "en": "Chinese silver pomfret",
    "scientificName": "Pampus chinensis",
    "family": "Stromateidae",
    "image": "../sport/assets/premium-fish/pampus-chinensis.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 280,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 280,
    "source": "https://www.heraldopenaccess.us/openaccess/pomfret-or-pompano-aquaculture-as-a-solution-to-the-tragedy-of-the-commons-in-hong-kong",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "又稱中國鯧，身體寬高、銀灰色；與白鯧是不同物種。香港市場研究列為具價值食用魚。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "larimichthys-crocea",
    "name": "大黃花",
    "en": "Large yellow croaker",
    "scientificName": "Larimichthys crocea",
    "family": "Sciaenidae",
    "image": "../sport/assets/premium-fish/larimichthys-crocea.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 230,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 230,
    "source": "https://seafood-guide.wwf.org.hk/en/node/1001",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "銀黃身體、腹部及魚鰭帶金黃色。市場亦有養殖供應，真實價格會隨來源和規格不同。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "trachinotus-blochii",
    "name": "黃立鯧",
    "en": "Snubnose pompano",
    "scientificName": "Trachinotus blochii",
    "family": "Carangidae",
    "image": "../sport/assets/premium-fish/trachinotus-blochii.svg",
    "min": 0.5,
    "max": 3,
    "hits": 6,
    "score": 180,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 180,
    "source": "https://www.heraldopenaccess.us/openaccess/pomfret-or-pompano-aquaculture-as-a-solution-to-the-tragedy-of-the-commons-in-hong-kong",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "沙泥底／近岸（遊戲分配）",
    "educationIntro": "吻部圓鈍、身體側扁，尾鰭分叉，鰭常帶黃色。香港有養殖及市場供應。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "cheung-chau",
      "harbour",
      "tung-wan",
      "lantau",
      "peng-chau",
      "discovery-bay"
    ]
  },
  {
    "id": "epinephelus-malabaricus",
    "name": "花鬼斑",
    "en": "Malabar grouper",
    "scientificName": "Epinephelus malabaricus",
    "family": "Serranidae",
    "image": "../sport/assets/premium-fish/epinephelus-malabaricus.svg",
    "min": 0.5,
    "max": 6,
    "hits": 8,
    "score": 300,
    "premium": true,
    "spawnWeight": 0.22,
    "sellPerKg": 300,
    "source": "https://library.enaca.org/Grouper/Publications/FWG01-99.pdf",
    "recordBasis": "香港海鮮市場／區域食用魚資料；包含進口或養殖魚種",
    "settingsBasis": "珍貴級別、出現率、重量、釣區與售價均為遊戲設定，售價不是港元市價",
    "artStatus": "original-vector-illustration",
    "habitat": "岩礁／外海（遊戲分配）",
    "educationIntro": "身體有細小黑斑和不規則深色斑塊。香港養殖文獻記錄此魚，俗名有時與青斑混用。\n\n香港海鮮市場／區域食用魚資料；包含進口或養殖魚種。\n\n珍貴魚：在遊戲中以紅色魚影顯示，較少出現，售價較高。圖片為物種特徵示意圖；遊戲價格不代表真實市價。",
    "educationRevision": "20260926-premium",
    "gameAreas": [
      "ninepins",
      "tung-lung",
      "po-toi",
      "lamma",
      "cheung-chau"
    ]
  }
];
function apply(config){
 config.fish=config.fish||[];
 for(const entry of fish){const prior=config.fish.find(f=>f.id===entry.id);if(prior)Object.assign(prior,structuredClone(entry));else config.fish.push(structuredClone(entry));}
 for(const area of config.areas||[]){const ids=fish.filter(f=>f.gameAreas.includes(area.id)).map(f=>f.id);area.fish=[...new Set([...(area.fish||[]),...ids])];}
 return config;
}
root.PremiumFish={fish,apply};
})(globalThis);
